// Code generated by oapi-codegen; DO NOT EDIT.

package helpers

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"reflect"
	"strings"
)

// JSONMerge merges two JSON-encoded objects. Fields from patch override
// fields in base. Both arguments must be valid JSON objects (or nil/null).
func JSONMerge(base, patch json.RawMessage) (json.RawMessage, error) {
	if len(base) == 0 || string(base) == "null" {
		return patch, nil
	}
	if len(patch) == 0 || string(patch) == "null" {
		return base, nil
	}

	var baseMap map[string]json.RawMessage
	if err := json.Unmarshal(base, &baseMap); err != nil {
		return nil, fmt.Errorf("JSONMerge: unmarshaling base: %w", err)
	}

	var patchMap map[string]json.RawMessage
	if err := json.Unmarshal(patch, &patchMap); err != nil {
		return nil, fmt.Errorf("JSONMerge: unmarshaling patch: %w", err)
	}

	for k, v := range patchMap {
		baseMap[k] = v
	}

	return json.Marshal(baseMap)
}

// MarshalForm marshals a struct into url.Values using the struct's json tags
// as field names. It handles nested structs, slices, pointers, and
// AdditionalProperties maps.
func MarshalForm(body interface{}) (url.Values, error) {
	ptrVal := reflect.Indirect(reflect.ValueOf(body))
	if ptrVal.Kind() != reflect.Struct {
		return nil, errors.New("form data body should be a struct")
	}
	tValue := ptrVal.Type()
	result := make(url.Values)
	for i := 0; i < tValue.NumField(); i++ {
		field := ptrVal.Field(i)
		tag := tValue.Field(i).Tag.Get("json")
		if !field.CanInterface() || tag == "-" {
			continue
		}
		omitEmpty := strings.HasSuffix(tag, ",omitempty")
		if omitEmpty && field.IsZero() {
			continue
		}
		tag = strings.Split(tag, ",")[0]
		marshalFormImpl(field, result, tag)
	}
	return result, nil
}

func marshalFormImpl(v reflect.Value, result url.Values, name string) {
	switch v.Kind() {
	case reflect.Interface, reflect.Ptr:
		if !v.IsNil() {
			marshalFormImpl(v.Elem(), result, name)
		}
	case reflect.Slice:
		for i := 0; i < v.Len(); i++ {
			marshalFormImpl(v.Index(i), result, fmt.Sprintf("%s[%v]", name, i))
		}
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			field := v.Type().Field(i)
			tag := field.Tag.Get("json")
			if field.Name == "AdditionalProperties" && tag == "-" {
				mapField := v.Field(i)
				if mapField.Kind() == reflect.Map {
					iter := mapField.MapRange()
					for iter.Next() {
						marshalFormImpl(iter.Value(), result, fmt.Sprintf("%s[%s]", name, iter.Key().String()))
					}
				}
				continue
			}
			if !v.Field(i).CanInterface() || tag == "-" {
				continue
			}
			tag = strings.Split(tag, ",")[0]
			marshalFormImpl(v.Field(i), result, fmt.Sprintf("%s[%s]", name, tag))
		}
	default:
		result[name] = append(result[name], fmt.Sprint(v.Interface()))
	}
}
