// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package videos

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ItemAudioTracksLanguageRequestBuilder builds and executes requests for operations under \videos\{videoId}\audio-tracks\language
type ItemAudioTracksLanguageRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByLang_code gets an item from the github.com/rixlhq/rixl-go/sdk.videos.item.audioTracks.language.item collection
// returns a *ItemAudioTracksLanguageWithLang_codeItemRequestBuilder when successful
func (m *ItemAudioTracksLanguageRequestBuilder) ByLang_code(lang_code string)(*ItemAudioTracksLanguageWithLang_codeItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if lang_code != "" {
        urlTplParams["lang_code"] = lang_code
    }
    return NewItemAudioTracksLanguageWithLang_codeItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewItemAudioTracksLanguageRequestBuilderInternal instantiates a new ItemAudioTracksLanguageRequestBuilder and sets the default values.
func NewItemAudioTracksLanguageRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemAudioTracksLanguageRequestBuilder) {
    m := &ItemAudioTracksLanguageRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/videos/{videoId}/audio-tracks/language", pathParameters),
    }
    return m
}
// NewItemAudioTracksLanguageRequestBuilder instantiates a new ItemAudioTracksLanguageRequestBuilder and sets the default values.
func NewItemAudioTracksLanguageRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemAudioTracksLanguageRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemAudioTracksLanguageRequestBuilderInternal(urlParams, requestAdapter)
}
