// Code generated by oapi-codegen; DO NOT EDIT.

package videos

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/rixlhq/rixl-go/sdk/models"
	oapiCodegenParamsPkg "github.com/rixlhq/rixl-go/sdk/runtime/params"
)

type uploadCompleteJSONRequestBody = models.GithubComRixlhqAPIInternalVideosHandlerUploadCompleteRequest

type uploadInitJSONRequestBody = models.VideoUploadInitRequest

type updateChaptersJSONRequestBody = models.UpdateChaptersRequest

// RequestEditorFn is the function signature for the RequestEditor callback function.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the OpenAPI spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction.
type ClientOption func(*Client) error

// NewClient creates a new Client with reasonable defaults.
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// Ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// Create httpClient if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientInterface is the interface specification for the client.
type ClientInterface interface {
	// List makes a GET request to /videos
	List(ctx context.Context, params *ListParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ListLanguages makes a GET request to /videos/languages
	ListLanguages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// UploadCompleteWithBody makes a POST request to /videos/upload/complete
	UploadCompleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	UploadComplete(ctx context.Context, body uploadCompleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// UploadInitWithBody makes a POST request to /videos/upload/init
	UploadInitWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	UploadInit(ctx context.Context, body uploadInitJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// Get makes a GET request to /videos/{videoId}
	Get(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// DeleteAudioTracks makes a DELETE request to /videos/{videoId}/audio-tracks
	DeleteAudioTracks(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ReplaceAudioTracksWithBody makes a POST request to /videos/{videoId}/audio-tracks
	ReplaceAudioTracksWithBody(ctx context.Context, videoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	// DeleteAudioTrackByLanguage makes a DELETE request to /videos/{videoId}/audio-tracks/language/{lang_code}
	DeleteAudioTrackByLanguage(ctx context.Context, videoId string, langCode string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// UpdateAudioTrackByLanguageWithBody makes a PUT request to /videos/{videoId}/audio-tracks/language/{lang_code}
	UpdateAudioTrackByLanguageWithBody(ctx context.Context, videoId string, langCode string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	// DeleteAudioTrack makes a DELETE request to /videos/{videoId}/audio-tracks/{trackId}
	DeleteAudioTrack(ctx context.Context, videoId string, trackId string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// DeleteChapters makes a DELETE request to /videos/{videoId}/chapters
	DeleteChapters(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// UpdateChaptersWithBody makes a PUT request to /videos/{videoId}/chapters
	UpdateChaptersWithBody(ctx context.Context, videoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	UpdateChapters(ctx context.Context, videoId string, body updateChaptersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// Delete makes a DELETE request to /videos/{videoId}/delete
	Delete(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// DeleteSubtitles makes a DELETE request to /videos/{videoId}/subtitles
	DeleteSubtitles(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ReplaceSubtitlesWithBody makes a POST request to /videos/{videoId}/subtitles
	ReplaceSubtitlesWithBody(ctx context.Context, videoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	// DeleteSubtitleByLanguage makes a DELETE request to /videos/{videoId}/subtitles/language/{lang_code}
	DeleteSubtitleByLanguage(ctx context.Context, videoId string, langCode string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// UpdateSubtitleByLanguageWithBody makes a PUT request to /videos/{videoId}/subtitles/language/{lang_code}
	UpdateSubtitleByLanguageWithBody(ctx context.Context, videoId string, langCode string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	// DeleteSubtitle makes a DELETE request to /videos/{videoId}/subtitles/{subtitleId}
	DeleteSubtitle(ctx context.Context, videoId string, subtitleId string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// UpdateThumbnailWithBody makes a PUT request to /videos/{videoId}/thumbnail
	UpdateThumbnailWithBody(ctx context.Context, videoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListParams defines parameters for List.
type ListParams struct {
	// limit (optional)
	Limit *int `form:"limit" json:"limit"`
	// offset (optional)
	Offset *int `form:"offset" json:"offset"`
	// sort (optional)
	Sort *string `form:"sort" json:"sort"`
	// order (optional)
	Order *string `form:"order" json:"order"`
}

// List makes a GET request to /videos
// List videos for a project
func (c *Client) List(ctx context.Context, params *ListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListLanguages makes a GET request to /videos/languages
// List available subtitle languages
func (c *Client) ListLanguages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListLanguagesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UploadCompleteWithBody makes a POST request to /videos/upload/complete
// Upload: Mark as complete
func (c *Client) UploadCompleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadCompleteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UploadComplete makes a POST request to /videos/upload/complete with application/json body
func (c *Client) UploadComplete(ctx context.Context, body uploadCompleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadCompleteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UploadInitWithBody makes a POST request to /videos/upload/init
// Upload: Init
func (c *Client) UploadInitWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadInitRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UploadInit makes a POST request to /videos/upload/init with application/json body
func (c *Client) UploadInit(ctx context.Context, body uploadInitJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadInitRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// Get makes a GET request to /videos/{videoId}
// Get a video
func (c *Client) Get(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRequest(c.Server, videoId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteAudioTracks makes a DELETE request to /videos/{videoId}/audio-tracks
// Delete all audio tracks
func (c *Client) DeleteAudioTracks(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAudioTracksRequest(c.Server, videoId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReplaceAudioTracksWithBody makes a POST request to /videos/{videoId}/audio-tracks
// Bulk upsert video audio tracks
func (c *Client) ReplaceAudioTracksWithBody(ctx context.Context, videoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceAudioTracksRequestWithBody(c.Server, videoId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteAudioTrackByLanguage makes a DELETE request to /videos/{videoId}/audio-tracks/language/{lang_code}
// Delete audio track by language
func (c *Client) DeleteAudioTrackByLanguage(ctx context.Context, videoId string, langCode string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAudioTrackByLanguageRequest(c.Server, videoId, langCode)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateAudioTrackByLanguageWithBody makes a PUT request to /videos/{videoId}/audio-tracks/language/{lang_code}
// Upsert video audio track
func (c *Client) UpdateAudioTrackByLanguageWithBody(ctx context.Context, videoId string, langCode string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateAudioTrackByLanguageRequestWithBody(c.Server, videoId, langCode, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteAudioTrack makes a DELETE request to /videos/{videoId}/audio-tracks/{trackId}
// Delete audio track
func (c *Client) DeleteAudioTrack(ctx context.Context, videoId string, trackId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAudioTrackRequest(c.Server, videoId, trackId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteChapters makes a DELETE request to /videos/{videoId}/chapters
// Delete video chapters
func (c *Client) DeleteChapters(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteChaptersRequest(c.Server, videoId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateChaptersWithBody makes a PUT request to /videos/{videoId}/chapters
// Update video chapters
func (c *Client) UpdateChaptersWithBody(ctx context.Context, videoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateChaptersRequestWithBody(c.Server, videoId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateChapters makes a PUT request to /videos/{videoId}/chapters with application/json body
func (c *Client) UpdateChapters(ctx context.Context, videoId string, body updateChaptersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateChaptersRequest(c.Server, videoId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// Delete makes a DELETE request to /videos/{videoId}/delete
// Delete video
func (c *Client) Delete(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteRequest(c.Server, videoId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteSubtitles makes a DELETE request to /videos/{videoId}/subtitles
// Delete all subtitles
func (c *Client) DeleteSubtitles(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteSubtitlesRequest(c.Server, videoId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReplaceSubtitlesWithBody makes a POST request to /videos/{videoId}/subtitles
// Bulk upsert video subtitles
func (c *Client) ReplaceSubtitlesWithBody(ctx context.Context, videoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceSubtitlesRequestWithBody(c.Server, videoId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteSubtitleByLanguage makes a DELETE request to /videos/{videoId}/subtitles/language/{lang_code}
// Delete subtitle by language
func (c *Client) DeleteSubtitleByLanguage(ctx context.Context, videoId string, langCode string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteSubtitleByLanguageRequest(c.Server, videoId, langCode)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateSubtitleByLanguageWithBody makes a PUT request to /videos/{videoId}/subtitles/language/{lang_code}
// Upsert video subtitle
func (c *Client) UpdateSubtitleByLanguageWithBody(ctx context.Context, videoId string, langCode string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateSubtitleByLanguageRequestWithBody(c.Server, videoId, langCode, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteSubtitle makes a DELETE request to /videos/{videoId}/subtitles/{subtitleId}
// Delete subtitle
func (c *Client) DeleteSubtitle(ctx context.Context, videoId string, subtitleId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteSubtitleRequest(c.Server, videoId, subtitleId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateThumbnailWithBody makes a PUT request to /videos/{videoId}/thumbnail
// Update video thumbnail
func (c *Client) UpdateThumbnailWithBody(ctx context.Context, videoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateThumbnailRequestWithBody(c.Server, videoId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListRequest creates a GET request for /videos
func NewListRequest(server string, params *ListParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.Limit != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("limit", *params.Limit, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "integer", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Offset != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("offset", *params.Offset, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "integer", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Sort != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("sort", *params.Sort, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Order != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("order", *params.Order, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListLanguagesRequest creates a GET request for /videos/languages
func NewListLanguagesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/languages")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUploadCompleteRequest creates a POST request for /videos/upload/complete with application/json body
func NewUploadCompleteRequest(server string, body uploadCompleteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUploadCompleteRequestWithBody(server, "application/json", bodyReader)
}

// NewUploadCompleteRequestWithBody creates a POST request for /videos/upload/complete with any body
func NewUploadCompleteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/upload/complete")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUploadInitRequest creates a POST request for /videos/upload/init with application/json body
func NewUploadInitRequest(server string, body uploadInitJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUploadInitRequestWithBody(server, "application/json", bodyReader)
}

// NewUploadInitRequestWithBody creates a POST request for /videos/upload/init with any body
func NewUploadInitRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/upload/init")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetRequest creates a GET request for /videos/{videoId}
func NewGetRequest(server string, videoId string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteAudioTracksRequest creates a DELETE request for /videos/{videoId}/audio-tracks
func NewDeleteAudioTracksRequest(server string, videoId string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/audio-tracks", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReplaceAudioTracksRequestWithBody creates a POST request for /videos/{videoId}/audio-tracks with any body
func NewReplaceAudioTracksRequestWithBody(server string, videoId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/audio-tracks", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAudioTrackByLanguageRequest creates a DELETE request for /videos/{videoId}/audio-tracks/language/{lang_code}
func NewDeleteAudioTrackByLanguageRequest(server string, videoId string, langCode string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("lang_code", langCode, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/audio-tracks/language/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateAudioTrackByLanguageRequestWithBody creates a PUT request for /videos/{videoId}/audio-tracks/language/{lang_code} with any body
func NewUpdateAudioTrackByLanguageRequestWithBody(server string, videoId string, langCode string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("lang_code", langCode, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/audio-tracks/language/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAudioTrackRequest creates a DELETE request for /videos/{videoId}/audio-tracks/{trackId}
func NewDeleteAudioTrackRequest(server string, videoId string, trackId string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("trackId", trackId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/audio-tracks/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteChaptersRequest creates a DELETE request for /videos/{videoId}/chapters
func NewDeleteChaptersRequest(server string, videoId string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/chapters", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateChaptersRequest creates a PUT request for /videos/{videoId}/chapters with application/json body
func NewUpdateChaptersRequest(server string, videoId string, body updateChaptersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateChaptersRequestWithBody(server, videoId, "application/json", bodyReader)
}

// NewUpdateChaptersRequestWithBody creates a PUT request for /videos/{videoId}/chapters with any body
func NewUpdateChaptersRequestWithBody(server string, videoId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/chapters", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteRequest creates a DELETE request for /videos/{videoId}/delete
func NewDeleteRequest(server string, videoId string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/delete", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteSubtitlesRequest creates a DELETE request for /videos/{videoId}/subtitles
func NewDeleteSubtitlesRequest(server string, videoId string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/subtitles", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReplaceSubtitlesRequestWithBody creates a POST request for /videos/{videoId}/subtitles with any body
func NewReplaceSubtitlesRequestWithBody(server string, videoId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/subtitles", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteSubtitleByLanguageRequest creates a DELETE request for /videos/{videoId}/subtitles/language/{lang_code}
func NewDeleteSubtitleByLanguageRequest(server string, videoId string, langCode string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("lang_code", langCode, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/subtitles/language/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateSubtitleByLanguageRequestWithBody creates a PUT request for /videos/{videoId}/subtitles/language/{lang_code} with any body
func NewUpdateSubtitleByLanguageRequestWithBody(server string, videoId string, langCode string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("lang_code", langCode, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/subtitles/language/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteSubtitleRequest creates a DELETE request for /videos/{videoId}/subtitles/{subtitleId}
func NewDeleteSubtitleRequest(server string, videoId string, subtitleId string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("subtitleId", subtitleId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/subtitles/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateThumbnailRequestWithBody creates a PUT request for /videos/{videoId}/thumbnail with any body
func NewUpdateThumbnailRequestWithBody(server string, videoId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("videoId", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/videos/%s/thumbnail", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// ClientHttpError represents an HTTP error response.
// The type parameter E is the type of the parsed error body.
type ClientHttpError[E any] struct {
	StatusCode int
	Body       E
	RawBody    []byte
}

func (e *ClientHttpError[E]) Error() string {
	return fmt.Sprintf("HTTP %d", e.StatusCode)
}

// SimpleClient wraps Client with typed responses for operations that have
// unambiguous response types. Methods return the success type directly,
// and HTTP errors are returned as *ClientHttpError[E] where E is the error type.
type SimpleClient struct {
	*Client
}

// NewSimpleClient creates a new SimpleClient which wraps a Client.
func NewSimpleClient(server string, opts ...ClientOption) (*SimpleClient, error) {
	inner, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &SimpleClient{Client: inner}, nil
}

// List makes a GET request to /videos and returns the parsed response.
// List videos for a project
// On success, returns the response body. On HTTP error, returns *ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse].
func (c *SimpleClient) List(ctx context.Context, params *ListParams, reqEditors ...RequestEditorFn) (models.PaginationPaginatedResponseVideo, error) {
	var result models.PaginationPaginatedResponseVideo
	resp, err := c.Client.List(ctx, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// Parse error response
	var errBody models.GithubComRixlhqAPIInternalErrorsErrorResponse
	_ = json.Unmarshal(rawBody, &errBody) // Best effort parse
	return result, &ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse]{
		StatusCode: resp.StatusCode,
		Body:       errBody,
		RawBody:    rawBody,
	}
}

// ListLanguages makes a GET request to /videos/languages and returns the parsed response.
// List available subtitle languages
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) ListLanguages(ctx context.Context, reqEditors ...RequestEditorFn) ([]models.InternalVideosHandlerSubtitlesLanguageResponse, error) {
	var result []models.InternalVideosHandlerSubtitlesLanguageResponse
	resp, err := c.Client.ListLanguages(ctx, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// UploadComplete makes a POST request to /videos/upload/complete and returns the parsed response.
// Upload: Mark as complete
// On success, returns the response body. On HTTP error, returns *ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse].
func (c *SimpleClient) UploadComplete(ctx context.Context, body uploadCompleteJSONRequestBody, reqEditors ...RequestEditorFn) (models.Video, error) {
	var result models.Video
	resp, err := c.Client.UploadComplete(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// Parse error response
	var errBody models.GithubComRixlhqAPIInternalErrorsErrorResponse
	_ = json.Unmarshal(rawBody, &errBody) // Best effort parse
	return result, &ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse]{
		StatusCode: resp.StatusCode,
		Body:       errBody,
		RawBody:    rawBody,
	}
}

// UploadInit makes a POST request to /videos/upload/init and returns the parsed response.
// Upload: Init
// On success, returns the response body. On HTTP error, returns *ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse].
func (c *SimpleClient) UploadInit(ctx context.Context, body uploadInitJSONRequestBody, reqEditors ...RequestEditorFn) (models.GithubComRixlhqAPIInternalVideosHandlerUploadInitResponse, error) {
	var result models.GithubComRixlhqAPIInternalVideosHandlerUploadInitResponse
	resp, err := c.Client.UploadInit(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// Parse error response
	var errBody models.GithubComRixlhqAPIInternalErrorsErrorResponse
	_ = json.Unmarshal(rawBody, &errBody) // Best effort parse
	return result, &ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse]{
		StatusCode: resp.StatusCode,
		Body:       errBody,
		RawBody:    rawBody,
	}
}

// Get makes a GET request to /videos/{videoId} and returns the parsed response.
// Get a video
// On success, returns the response body. On HTTP error, returns *ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse].
func (c *SimpleClient) Get(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (models.Video, error) {
	var result models.Video
	resp, err := c.Client.Get(ctx, videoId, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// Parse error response
	var errBody models.GithubComRixlhqAPIInternalErrorsErrorResponse
	_ = json.Unmarshal(rawBody, &errBody) // Best effort parse
	return result, &ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse]{
		StatusCode: resp.StatusCode,
		Body:       errBody,
		RawBody:    rawBody,
	}
}

// DeleteAudioTracks makes a DELETE request to /videos/{videoId}/audio-tracks and returns the parsed response.
// Delete all audio tracks
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) DeleteAudioTracks(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (models.AudioTrackDelete, error) {
	var result models.AudioTrackDelete
	resp, err := c.Client.DeleteAudioTracks(ctx, videoId, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// DeleteAudioTrackByLanguage makes a DELETE request to /videos/{videoId}/audio-tracks/language/{lang_code} and returns the parsed response.
// Delete audio track by language
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) DeleteAudioTrackByLanguage(ctx context.Context, videoId string, langCode string, reqEditors ...RequestEditorFn) (models.AudioTrackDelete, error) {
	var result models.AudioTrackDelete
	resp, err := c.Client.DeleteAudioTrackByLanguage(ctx, videoId, langCode, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// DeleteAudioTrack makes a DELETE request to /videos/{videoId}/audio-tracks/{trackId} and returns the parsed response.
// Delete audio track
// On success, returns the response body. On HTTP error, returns *ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse].
func (c *SimpleClient) DeleteAudioTrack(ctx context.Context, videoId string, trackId string, reqEditors ...RequestEditorFn) (models.AudioTrackDelete, error) {
	var result models.AudioTrackDelete
	resp, err := c.Client.DeleteAudioTrack(ctx, videoId, trackId, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// Parse error response
	var errBody models.GithubComRixlhqAPIInternalErrorsErrorResponse
	_ = json.Unmarshal(rawBody, &errBody) // Best effort parse
	return result, &ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse]{
		StatusCode: resp.StatusCode,
		Body:       errBody,
		RawBody:    rawBody,
	}
}

// DeleteChapters makes a DELETE request to /videos/{videoId}/chapters and returns the parsed response.
// Delete video chapters
// On success, returns the response body. On HTTP error, returns *ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse].
func (c *SimpleClient) DeleteChapters(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (models.UpdateChaptersResponse, error) {
	var result models.UpdateChaptersResponse
	resp, err := c.Client.DeleteChapters(ctx, videoId, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// Parse error response
	var errBody models.GithubComRixlhqAPIInternalErrorsErrorResponse
	_ = json.Unmarshal(rawBody, &errBody) // Best effort parse
	return result, &ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse]{
		StatusCode: resp.StatusCode,
		Body:       errBody,
		RawBody:    rawBody,
	}
}

// UpdateChapters makes a PUT request to /videos/{videoId}/chapters and returns the parsed response.
// Update video chapters
// On success, returns the response body. On HTTP error, returns *ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse].
func (c *SimpleClient) UpdateChapters(ctx context.Context, videoId string, body updateChaptersJSONRequestBody, reqEditors ...RequestEditorFn) (models.UpdateChaptersResponse, error) {
	var result models.UpdateChaptersResponse
	resp, err := c.Client.UpdateChapters(ctx, videoId, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// Parse error response
	var errBody models.GithubComRixlhqAPIInternalErrorsErrorResponse
	_ = json.Unmarshal(rawBody, &errBody) // Best effort parse
	return result, &ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse]{
		StatusCode: resp.StatusCode,
		Body:       errBody,
		RawBody:    rawBody,
	}
}

// DeleteSubtitles makes a DELETE request to /videos/{videoId}/subtitles and returns the parsed response.
// Delete all subtitles
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) DeleteSubtitles(ctx context.Context, videoId string, reqEditors ...RequestEditorFn) (models.SubtitleDelete, error) {
	var result models.SubtitleDelete
	resp, err := c.Client.DeleteSubtitles(ctx, videoId, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// DeleteSubtitleByLanguage makes a DELETE request to /videos/{videoId}/subtitles/language/{lang_code} and returns the parsed response.
// Delete subtitle by language
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) DeleteSubtitleByLanguage(ctx context.Context, videoId string, langCode string, reqEditors ...RequestEditorFn) (models.SubtitleDelete, error) {
	var result models.SubtitleDelete
	resp, err := c.Client.DeleteSubtitleByLanguage(ctx, videoId, langCode, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// DeleteSubtitle makes a DELETE request to /videos/{videoId}/subtitles/{subtitleId} and returns the parsed response.
// Delete subtitle
// On success, returns the response body. On HTTP error, returns *ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse].
func (c *SimpleClient) DeleteSubtitle(ctx context.Context, videoId string, subtitleId string, reqEditors ...RequestEditorFn) (models.SubtitleDelete, error) {
	var result models.SubtitleDelete
	resp, err := c.Client.DeleteSubtitle(ctx, videoId, subtitleId, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// Parse error response
	var errBody models.GithubComRixlhqAPIInternalErrorsErrorResponse
	_ = json.Unmarshal(rawBody, &errBody) // Best effort parse
	return result, &ClientHttpError[models.GithubComRixlhqAPIInternalErrorsErrorResponse]{
		StatusCode: resp.StatusCode,
		Body:       errBody,
		RawBody:    rawBody,
	}
}
