// Code generated by oapi-codegen; DO NOT EDIT.

package customdomains

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/rixlhq/rixl-go/sdk/models"
	oapiCodegenParamsPkg "github.com/rixlhq/rixl-go/sdk/runtime/params"
)

type CreateDomainVerificationJSONRequestBody = any

type SetDomainAutoJoinJSONRequestBody = any

// RequestEditorFn is the function signature for the RequestEditor callback function.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the OpenAPI spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction.
type ClientOption func(*Client) error

// NewClient creates a new Client with reasonable defaults.
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// Ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// Create httpClient if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientInterface is the interface specification for the client.
type ClientInterface interface {
	// RemoveDomain makes a DELETE request to /auth/v1/memberships/{org_id}/domain
	RemoveDomain(ctx context.Context, orgId string, params *RemoveDomainParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetDomainStatus makes a GET request to /auth/v1/memberships/{org_id}/domain
	GetDomainStatus(ctx context.Context, orgId string, params *GetDomainStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetDomainAutoJoin makes a GET request to /auth/v1/memberships/{org_id}/domain/auto-join
	GetDomainAutoJoin(ctx context.Context, orgId string, params *GetDomainAutoJoinParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// CheckDomainVerification makes a POST request to /auth/v1/memberships/{org_id}/domain/verify
	CheckDomainVerification(ctx context.Context, orgId string, params *CheckDomainVerificationParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// CreateDomainVerificationWithBody makes a POST request to /auth/v1/memberships/{user.org_id}/domain
	CreateDomainVerificationWithBody(ctx context.Context, userOrgId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	CreateDomainVerification(ctx context.Context, userOrgId string, body CreateDomainVerificationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// SetDomainAutoJoinWithBody makes a PUT request to /auth/v1/memberships/{user.org_id}/domain/auto-join
	SetDomainAutoJoinWithBody(ctx context.Context, userOrgId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	SetDomainAutoJoin(ctx context.Context, userOrgId string, body SetDomainAutoJoinJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// RemoveDomainParams defines parameters for RemoveDomain.
type RemoveDomainParams struct {
	// user_id (optional)
	UserId *string `form:"user_id" json:"user_id"`
}

// GetDomainStatusParams defines parameters for GetDomainStatus.
type GetDomainStatusParams struct {
	// user_id (optional)
	UserId *string `form:"user_id" json:"user_id"`
}

// GetDomainAutoJoinParams defines parameters for GetDomainAutoJoin.
type GetDomainAutoJoinParams struct {
	// user_id (optional)
	UserId *string `form:"user_id" json:"user_id"`
}

// CheckDomainVerificationParams defines parameters for CheckDomainVerification.
type CheckDomainVerificationParams struct {
	// user_id (optional)
	UserId *string `form:"user_id" json:"user_id"`
}

// RemoveDomain makes a DELETE request to /auth/v1/memberships/{org_id}/domain
// RemoveDomain
func (c *Client) RemoveDomain(ctx context.Context, orgId string, params *RemoveDomainParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRemoveDomainRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetDomainStatus makes a GET request to /auth/v1/memberships/{org_id}/domain
// GetDomainStatus
func (c *Client) GetDomainStatus(ctx context.Context, orgId string, params *GetDomainStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDomainStatusRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetDomainAutoJoin makes a GET request to /auth/v1/memberships/{org_id}/domain/auto-join
// GetDomainAutoJoin
func (c *Client) GetDomainAutoJoin(ctx context.Context, orgId string, params *GetDomainAutoJoinParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDomainAutoJoinRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CheckDomainVerification makes a POST request to /auth/v1/memberships/{org_id}/domain/verify
// CheckDomainVerification
func (c *Client) CheckDomainVerification(ctx context.Context, orgId string, params *CheckDomainVerificationParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckDomainVerificationRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateDomainVerificationWithBody makes a POST request to /auth/v1/memberships/{user.org_id}/domain
// CreateDomainVerification
func (c *Client) CreateDomainVerificationWithBody(ctx context.Context, userOrgId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDomainVerificationRequestWithBody(c.Server, userOrgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateDomainVerification makes a POST request to /auth/v1/memberships/{user.org_id}/domain with application/json body
func (c *Client) CreateDomainVerification(ctx context.Context, userOrgId string, body CreateDomainVerificationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDomainVerificationRequest(c.Server, userOrgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SetDomainAutoJoinWithBody makes a PUT request to /auth/v1/memberships/{user.org_id}/domain/auto-join
// SetDomainAutoJoin
func (c *Client) SetDomainAutoJoinWithBody(ctx context.Context, userOrgId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetDomainAutoJoinRequestWithBody(c.Server, userOrgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SetDomainAutoJoin makes a PUT request to /auth/v1/memberships/{user.org_id}/domain/auto-join with application/json body
func (c *Client) SetDomainAutoJoin(ctx context.Context, userOrgId string, body SetDomainAutoJoinJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetDomainAutoJoinRequest(c.Server, userOrgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRemoveDomainRequest creates a DELETE request for /auth/v1/memberships/{org_id}/domain
func NewRemoveDomainRequest(server string, orgId string, params *RemoveDomainParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("org_id", orgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/domain", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user_id", *params.UserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDomainStatusRequest creates a GET request for /auth/v1/memberships/{org_id}/domain
func NewGetDomainStatusRequest(server string, orgId string, params *GetDomainStatusParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("org_id", orgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/domain", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user_id", *params.UserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDomainAutoJoinRequest creates a GET request for /auth/v1/memberships/{org_id}/domain/auto-join
func NewGetDomainAutoJoinRequest(server string, orgId string, params *GetDomainAutoJoinParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("org_id", orgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/domain/auto-join", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user_id", *params.UserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCheckDomainVerificationRequest creates a POST request for /auth/v1/memberships/{org_id}/domain/verify
func NewCheckDomainVerificationRequest(server string, orgId string, params *CheckDomainVerificationParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("org_id", orgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/domain/verify", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user_id", *params.UserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateDomainVerificationRequest creates a POST request for /auth/v1/memberships/{user.org_id}/domain with application/json body
func NewCreateDomainVerificationRequest(server string, userOrgId string, body CreateDomainVerificationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateDomainVerificationRequestWithBody(server, userOrgId, "application/json", bodyReader)
}

// NewCreateDomainVerificationRequestWithBody creates a POST request for /auth/v1/memberships/{user.org_id}/domain with any body
func NewCreateDomainVerificationRequestWithBody(server string, userOrgId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("user.org_id", userOrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/domain", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSetDomainAutoJoinRequest creates a PUT request for /auth/v1/memberships/{user.org_id}/domain/auto-join with application/json body
func NewSetDomainAutoJoinRequest(server string, userOrgId string, body SetDomainAutoJoinJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetDomainAutoJoinRequestWithBody(server, userOrgId, "application/json", bodyReader)
}

// NewSetDomainAutoJoinRequestWithBody creates a PUT request for /auth/v1/memberships/{user.org_id}/domain/auto-join with any body
func NewSetDomainAutoJoinRequestWithBody(server string, userOrgId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("user.org_id", userOrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/domain/auto-join", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// ClientHttpError represents an HTTP error response.
// The type parameter E is the type of the parsed error body.
type ClientHttpError[E any] struct {
	StatusCode int
	Body       E
	RawBody    []byte
}

func (e *ClientHttpError[E]) Error() string {
	return fmt.Sprintf("HTTP %d", e.StatusCode)
}

// SimpleClient wraps Client with typed responses for operations that have
// unambiguous response types. Methods return the success type directly,
// and HTTP errors are returned as *ClientHttpError[E] where E is the error type.
type SimpleClient struct {
	*Client
}

// NewSimpleClient creates a new SimpleClient which wraps a Client.
func NewSimpleClient(server string, opts ...ClientOption) (*SimpleClient, error) {
	inner, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &SimpleClient{Client: inner}, nil
}

// RemoveDomain makes a DELETE request to /auth/v1/memberships/{org_id}/domain and returns the parsed response.
// RemoveDomain
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) RemoveDomain(ctx context.Context, orgId string, params *RemoveDomainParams, reqEditors ...RequestEditorFn) (models.GoogleProtobufEmpty, error) {
	var result models.GoogleProtobufEmpty
	resp, err := c.Client.RemoveDomain(ctx, orgId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// GetDomainStatus makes a GET request to /auth/v1/memberships/{org_id}/domain and returns the parsed response.
// GetDomainStatus
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetDomainStatus(ctx context.Context, orgId string, params *GetDomainStatusParams, reqEditors ...RequestEditorFn) (models.AuthV1DomainResponse, error) {
	var result models.AuthV1DomainResponse
	resp, err := c.Client.GetDomainStatus(ctx, orgId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// GetDomainAutoJoin makes a GET request to /auth/v1/memberships/{org_id}/domain/auto-join and returns the parsed response.
// GetDomainAutoJoin
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetDomainAutoJoin(ctx context.Context, orgId string, params *GetDomainAutoJoinParams, reqEditors ...RequestEditorFn) (models.AuthV1AutoJoinSetting, error) {
	var result models.AuthV1AutoJoinSetting
	resp, err := c.Client.GetDomainAutoJoin(ctx, orgId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// CheckDomainVerification makes a POST request to /auth/v1/memberships/{org_id}/domain/verify and returns the parsed response.
// CheckDomainVerification
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) CheckDomainVerification(ctx context.Context, orgId string, params *CheckDomainVerificationParams, reqEditors ...RequestEditorFn) (models.AuthV1DomainResponse, error) {
	var result models.AuthV1DomainResponse
	resp, err := c.Client.CheckDomainVerification(ctx, orgId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// CreateDomainVerification makes a POST request to /auth/v1/memberships/{user.org_id}/domain and returns the parsed response.
// CreateDomainVerification
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) CreateDomainVerification(ctx context.Context, userOrgId string, body CreateDomainVerificationJSONRequestBody, reqEditors ...RequestEditorFn) (models.AuthV1DomainResponse, error) {
	var result models.AuthV1DomainResponse
	resp, err := c.Client.CreateDomainVerification(ctx, userOrgId, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// SetDomainAutoJoin makes a PUT request to /auth/v1/memberships/{user.org_id}/domain/auto-join and returns the parsed response.
// SetDomainAutoJoin
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) SetDomainAutoJoin(ctx context.Context, userOrgId string, body SetDomainAutoJoinJSONRequestBody, reqEditors ...RequestEditorFn) (models.AuthV1AutoJoinSetting, error) {
	var result models.AuthV1AutoJoinSetting
	resp, err := c.Client.SetDomainAutoJoin(ctx, userOrgId, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}
