// Code generated by oapi-codegen; DO NOT EDIT.

package accesspolicies

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/rixlhq/rixl-go/sdk/models"
	oapiCodegenParamsPkg "github.com/rixlhq/rixl-go/sdk/runtime/params"
)

type CreatePolicyJSONRequestBody = any

type UpdatePolicyJSONRequestBody = any

type AttachPolicyJSONRequestBody = any

// RequestEditorFn is the function signature for the RequestEditor callback function.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the OpenAPI spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction.
type ClientOption func(*Client) error

// NewClient creates a new Client with reasonable defaults.
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// Ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// Create httpClient if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientInterface is the interface specification for the client.
type ClientInterface interface {
	// ListPolicies makes a GET request to /auth/v1/memberships/{org_id}/policies
	ListPolicies(ctx context.Context, orgId string, params *ListPoliciesParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ListUserPolicies makes a GET request to /auth/v1/memberships/{user.org_id}/members/{member_id}/policies
	ListUserPolicies(ctx context.Context, userOrgId string, memberId string, params *ListUserPoliciesParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// CreatePolicyWithBody makes a POST request to /auth/v1/memberships/{user.org_id}/policies
	CreatePolicyWithBody(ctx context.Context, userOrgId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	CreatePolicy(ctx context.Context, userOrgId string, body CreatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// DetachPolicy makes a DELETE request to /auth/v1/memberships/{user.org_id}/policies/attachments/{attachment_id}
	DetachPolicy(ctx context.Context, userOrgId string, attachmentId string, params *DetachPolicyParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// DeletePolicy makes a DELETE request to /auth/v1/memberships/{user.org_id}/policies/{policy_id}
	DeletePolicy(ctx context.Context, userOrgId string, policyId string, params *DeletePolicyParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetPolicy makes a GET request to /auth/v1/memberships/{user.org_id}/policies/{policy_id}
	GetPolicy(ctx context.Context, userOrgId string, policyId string, params *GetPolicyParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// UpdatePolicyWithBody makes a PUT request to /auth/v1/memberships/{user.org_id}/policies/{policy_id}
	UpdatePolicyWithBody(ctx context.Context, userOrgId string, policyId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	UpdatePolicy(ctx context.Context, userOrgId string, policyId string, body UpdatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ListPolicyAttachments makes a GET request to /auth/v1/memberships/{user.org_id}/policies/{policy_id}/attachments
	ListPolicyAttachments(ctx context.Context, userOrgId string, policyId string, params *ListPolicyAttachmentsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// AttachPolicyWithBody makes a POST request to /auth/v1/memberships/{user.org_id}/policies/{policy_id}/attachments
	AttachPolicyWithBody(ctx context.Context, userOrgId string, policyId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	AttachPolicy(ctx context.Context, userOrgId string, policyId string, body AttachPolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ListPermissionRegistry makes a GET request to /auth/v1/policies/permissions
	ListPermissionRegistry(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListPoliciesParams defines parameters for ListPolicies.
type ListPoliciesParams struct {
	// user_id (optional)
	UserId *string `form:"user_id" json:"user_id"`
}

// ListUserPoliciesParams defines parameters for ListUserPolicies.
type ListUserPoliciesParams struct {
	// user.user_id (optional)
	UserUserId *string `form:"user.user_id" json:"user.user_id"`
}

// DetachPolicyParams defines parameters for DetachPolicy.
type DetachPolicyParams struct {
	// user.user_id (optional)
	UserUserId *string `form:"user.user_id" json:"user.user_id"`
}

// DeletePolicyParams defines parameters for DeletePolicy.
type DeletePolicyParams struct {
	// user.user_id (optional)
	UserUserId *string `form:"user.user_id" json:"user.user_id"`
}

// GetPolicyParams defines parameters for GetPolicy.
type GetPolicyParams struct {
	// user.user_id (optional)
	UserUserId *string `form:"user.user_id" json:"user.user_id"`
}

// ListPolicyAttachmentsParams defines parameters for ListPolicyAttachments.
type ListPolicyAttachmentsParams struct {
	// user.user_id (optional)
	UserUserId *string `form:"user.user_id" json:"user.user_id"`
}

// ListPolicies makes a GET request to /auth/v1/memberships/{org_id}/policies
// ListPolicies
func (c *Client) ListPolicies(ctx context.Context, orgId string, params *ListPoliciesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPoliciesRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListUserPolicies makes a GET request to /auth/v1/memberships/{user.org_id}/members/{member_id}/policies
// ListUserPolicies
func (c *Client) ListUserPolicies(ctx context.Context, userOrgId string, memberId string, params *ListUserPoliciesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListUserPoliciesRequest(c.Server, userOrgId, memberId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePolicyWithBody makes a POST request to /auth/v1/memberships/{user.org_id}/policies
// CreatePolicy
func (c *Client) CreatePolicyWithBody(ctx context.Context, userOrgId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePolicyRequestWithBody(c.Server, userOrgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePolicy makes a POST request to /auth/v1/memberships/{user.org_id}/policies with application/json body
func (c *Client) CreatePolicy(ctx context.Context, userOrgId string, body CreatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePolicyRequest(c.Server, userOrgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DetachPolicy makes a DELETE request to /auth/v1/memberships/{user.org_id}/policies/attachments/{attachment_id}
// DetachPolicy
func (c *Client) DetachPolicy(ctx context.Context, userOrgId string, attachmentId string, params *DetachPolicyParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDetachPolicyRequest(c.Server, userOrgId, attachmentId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeletePolicy makes a DELETE request to /auth/v1/memberships/{user.org_id}/policies/{policy_id}
// DeletePolicy
func (c *Client) DeletePolicy(ctx context.Context, userOrgId string, policyId string, params *DeletePolicyParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeletePolicyRequest(c.Server, userOrgId, policyId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetPolicy makes a GET request to /auth/v1/memberships/{user.org_id}/policies/{policy_id}
// GetPolicy
func (c *Client) GetPolicy(ctx context.Context, userOrgId string, policyId string, params *GetPolicyParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPolicyRequest(c.Server, userOrgId, policyId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdatePolicyWithBody makes a PUT request to /auth/v1/memberships/{user.org_id}/policies/{policy_id}
// UpdatePolicy
func (c *Client) UpdatePolicyWithBody(ctx context.Context, userOrgId string, policyId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdatePolicyRequestWithBody(c.Server, userOrgId, policyId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdatePolicy makes a PUT request to /auth/v1/memberships/{user.org_id}/policies/{policy_id} with application/json body
func (c *Client) UpdatePolicy(ctx context.Context, userOrgId string, policyId string, body UpdatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdatePolicyRequest(c.Server, userOrgId, policyId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListPolicyAttachments makes a GET request to /auth/v1/memberships/{user.org_id}/policies/{policy_id}/attachments
// ListPolicyAttachments
func (c *Client) ListPolicyAttachments(ctx context.Context, userOrgId string, policyId string, params *ListPolicyAttachmentsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPolicyAttachmentsRequest(c.Server, userOrgId, policyId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AttachPolicyWithBody makes a POST request to /auth/v1/memberships/{user.org_id}/policies/{policy_id}/attachments
// AttachPolicy
func (c *Client) AttachPolicyWithBody(ctx context.Context, userOrgId string, policyId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAttachPolicyRequestWithBody(c.Server, userOrgId, policyId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AttachPolicy makes a POST request to /auth/v1/memberships/{user.org_id}/policies/{policy_id}/attachments with application/json body
func (c *Client) AttachPolicy(ctx context.Context, userOrgId string, policyId string, body AttachPolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAttachPolicyRequest(c.Server, userOrgId, policyId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListPermissionRegistry makes a GET request to /auth/v1/policies/permissions
// ListPermissionRegistry
func (c *Client) ListPermissionRegistry(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPermissionRegistryRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListPoliciesRequest creates a GET request for /auth/v1/memberships/{org_id}/policies
func NewListPoliciesRequest(server string, orgId string, params *ListPoliciesParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("org_id", orgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/policies", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user_id", *params.UserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListUserPoliciesRequest creates a GET request for /auth/v1/memberships/{user.org_id}/members/{member_id}/policies
func NewListUserPoliciesRequest(server string, userOrgId string, memberId string, params *ListUserPoliciesParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("user.org_id", userOrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("member_id", memberId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/members/%s/policies", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserUserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user.user_id", *params.UserUserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreatePolicyRequest creates a POST request for /auth/v1/memberships/{user.org_id}/policies with application/json body
func NewCreatePolicyRequest(server string, userOrgId string, body CreatePolicyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePolicyRequestWithBody(server, userOrgId, "application/json", bodyReader)
}

// NewCreatePolicyRequestWithBody creates a POST request for /auth/v1/memberships/{user.org_id}/policies with any body
func NewCreatePolicyRequestWithBody(server string, userOrgId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("user.org_id", userOrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/policies", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDetachPolicyRequest creates a DELETE request for /auth/v1/memberships/{user.org_id}/policies/attachments/{attachment_id}
func NewDetachPolicyRequest(server string, userOrgId string, attachmentId string, params *DetachPolicyParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("user.org_id", userOrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("attachment_id", attachmentId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/policies/attachments/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserUserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user.user_id", *params.UserUserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeletePolicyRequest creates a DELETE request for /auth/v1/memberships/{user.org_id}/policies/{policy_id}
func NewDeletePolicyRequest(server string, userOrgId string, policyId string, params *DeletePolicyParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("user.org_id", userOrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("policy_id", policyId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/policies/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserUserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user.user_id", *params.UserUserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPolicyRequest creates a GET request for /auth/v1/memberships/{user.org_id}/policies/{policy_id}
func NewGetPolicyRequest(server string, userOrgId string, policyId string, params *GetPolicyParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("user.org_id", userOrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("policy_id", policyId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/policies/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserUserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user.user_id", *params.UserUserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdatePolicyRequest creates a PUT request for /auth/v1/memberships/{user.org_id}/policies/{policy_id} with application/json body
func NewUpdatePolicyRequest(server string, userOrgId string, policyId string, body UpdatePolicyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdatePolicyRequestWithBody(server, userOrgId, policyId, "application/json", bodyReader)
}

// NewUpdatePolicyRequestWithBody creates a PUT request for /auth/v1/memberships/{user.org_id}/policies/{policy_id} with any body
func NewUpdatePolicyRequestWithBody(server string, userOrgId string, policyId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("user.org_id", userOrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("policy_id", policyId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/policies/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListPolicyAttachmentsRequest creates a GET request for /auth/v1/memberships/{user.org_id}/policies/{policy_id}/attachments
func NewListPolicyAttachmentsRequest(server string, userOrgId string, policyId string, params *ListPolicyAttachmentsParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("user.org_id", userOrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("policy_id", policyId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/policies/%s/attachments", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserUserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user.user_id", *params.UserUserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAttachPolicyRequest creates a POST request for /auth/v1/memberships/{user.org_id}/policies/{policy_id}/attachments with application/json body
func NewAttachPolicyRequest(server string, userOrgId string, policyId string, body AttachPolicyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAttachPolicyRequestWithBody(server, userOrgId, policyId, "application/json", bodyReader)
}

// NewAttachPolicyRequestWithBody creates a POST request for /auth/v1/memberships/{user.org_id}/policies/{policy_id}/attachments with any body
func NewAttachPolicyRequestWithBody(server string, userOrgId string, policyId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("user.org_id", userOrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("policy_id", policyId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/memberships/%s/policies/%s/attachments", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListPermissionRegistryRequest creates a GET request for /auth/v1/policies/permissions
func NewListPermissionRegistryRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/policies/permissions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// ClientHttpError represents an HTTP error response.
// The type parameter E is the type of the parsed error body.
type ClientHttpError[E any] struct {
	StatusCode int
	Body       E
	RawBody    []byte
}

func (e *ClientHttpError[E]) Error() string {
	return fmt.Sprintf("HTTP %d", e.StatusCode)
}

// SimpleClient wraps Client with typed responses for operations that have
// unambiguous response types. Methods return the success type directly,
// and HTTP errors are returned as *ClientHttpError[E] where E is the error type.
type SimpleClient struct {
	*Client
}

// NewSimpleClient creates a new SimpleClient which wraps a Client.
func NewSimpleClient(server string, opts ...ClientOption) (*SimpleClient, error) {
	inner, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &SimpleClient{Client: inner}, nil
}

// ListPolicies makes a GET request to /auth/v1/memberships/{org_id}/policies and returns the parsed response.
// ListPolicies
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) ListPolicies(ctx context.Context, orgId string, params *ListPoliciesParams, reqEditors ...RequestEditorFn) (models.AuthV1ListPoliciesResponse, error) {
	var result models.AuthV1ListPoliciesResponse
	resp, err := c.Client.ListPolicies(ctx, orgId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// ListUserPolicies makes a GET request to /auth/v1/memberships/{user.org_id}/members/{member_id}/policies and returns the parsed response.
// ListUserPolicies
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) ListUserPolicies(ctx context.Context, userOrgId string, memberId string, params *ListUserPoliciesParams, reqEditors ...RequestEditorFn) (models.AuthV1MemberPoliciesResponse, error) {
	var result models.AuthV1MemberPoliciesResponse
	resp, err := c.Client.ListUserPolicies(ctx, userOrgId, memberId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// CreatePolicy makes a POST request to /auth/v1/memberships/{user.org_id}/policies and returns the parsed response.
// CreatePolicy
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) CreatePolicy(ctx context.Context, userOrgId string, body CreatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (models.AuthV1Policy, error) {
	var result models.AuthV1Policy
	resp, err := c.Client.CreatePolicy(ctx, userOrgId, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// DetachPolicy makes a DELETE request to /auth/v1/memberships/{user.org_id}/policies/attachments/{attachment_id} and returns the parsed response.
// DetachPolicy
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) DetachPolicy(ctx context.Context, userOrgId string, attachmentId string, params *DetachPolicyParams, reqEditors ...RequestEditorFn) (models.GoogleProtobufEmpty, error) {
	var result models.GoogleProtobufEmpty
	resp, err := c.Client.DetachPolicy(ctx, userOrgId, attachmentId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// DeletePolicy makes a DELETE request to /auth/v1/memberships/{user.org_id}/policies/{policy_id} and returns the parsed response.
// DeletePolicy
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) DeletePolicy(ctx context.Context, userOrgId string, policyId string, params *DeletePolicyParams, reqEditors ...RequestEditorFn) (models.GoogleProtobufEmpty, error) {
	var result models.GoogleProtobufEmpty
	resp, err := c.Client.DeletePolicy(ctx, userOrgId, policyId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// GetPolicy makes a GET request to /auth/v1/memberships/{user.org_id}/policies/{policy_id} and returns the parsed response.
// GetPolicy
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetPolicy(ctx context.Context, userOrgId string, policyId string, params *GetPolicyParams, reqEditors ...RequestEditorFn) (models.AuthV1Policy, error) {
	var result models.AuthV1Policy
	resp, err := c.Client.GetPolicy(ctx, userOrgId, policyId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// UpdatePolicy makes a PUT request to /auth/v1/memberships/{user.org_id}/policies/{policy_id} and returns the parsed response.
// UpdatePolicy
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) UpdatePolicy(ctx context.Context, userOrgId string, policyId string, body UpdatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (models.AuthV1Policy, error) {
	var result models.AuthV1Policy
	resp, err := c.Client.UpdatePolicy(ctx, userOrgId, policyId, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// ListPolicyAttachments makes a GET request to /auth/v1/memberships/{user.org_id}/policies/{policy_id}/attachments and returns the parsed response.
// ListPolicyAttachments
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) ListPolicyAttachments(ctx context.Context, userOrgId string, policyId string, params *ListPolicyAttachmentsParams, reqEditors ...RequestEditorFn) (models.AuthV1ListAttachmentsResponse, error) {
	var result models.AuthV1ListAttachmentsResponse
	resp, err := c.Client.ListPolicyAttachments(ctx, userOrgId, policyId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// AttachPolicy makes a POST request to /auth/v1/memberships/{user.org_id}/policies/{policy_id}/attachments and returns the parsed response.
// AttachPolicy
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) AttachPolicy(ctx context.Context, userOrgId string, policyId string, body AttachPolicyJSONRequestBody, reqEditors ...RequestEditorFn) (models.AuthV1PolicyAttachment, error) {
	var result models.AuthV1PolicyAttachment
	resp, err := c.Client.AttachPolicy(ctx, userOrgId, policyId, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// ListPermissionRegistry makes a GET request to /auth/v1/policies/permissions and returns the parsed response.
// ListPermissionRegistry
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) ListPermissionRegistry(ctx context.Context, reqEditors ...RequestEditorFn) (models.AuthV1PermissionRegistryResponse, error) {
	var result models.AuthV1PermissionRegistryResponse
	resp, err := c.Client.ListPermissionRegistry(ctx, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}
