// Code generated by oapi-codegen; DO NOT EDIT.

package heatmaps

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/rixlhq/rixl-go/sdk/models"
	oapiCodegenParamsPkg "github.com/rixlhq/rixl-go/sdk/runtime/params"
)

// RequestEditorFn is the function signature for the RequestEditor callback function.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the OpenAPI spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction.
type ClientOption func(*Client) error

// NewClient creates a new Client with reasonable defaults.
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// Ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// Create httpClient if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientInterface is the interface specification for the client.
type ClientInterface interface {
	// GetVideoHeatmap makes a GET request to /analytics/v1/videos/{video_id}/heatmap
	GetVideoHeatmap(ctx context.Context, videoId string, params *GetVideoHeatmapParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetHotSegments makes a GET request to /analytics/v1/videos/{video_id}/hot-segments
	GetHotSegments(ctx context.Context, videoId string, params *GetHotSegmentsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetVideoHeatmapParams defines parameters for GetVideoHeatmap.
type GetVideoHeatmapParams struct {
	// buckets (optional)
	Buckets *int32 `form:"buckets" json:"buckets"`
	// range.start (optional)
	RangeStart *string `form:"range.start" json:"range.start"`
	// range.end (optional)
	RangeEnd *string `form:"range.end" json:"range.end"`
}

// GetHotSegmentsParams defines parameters for GetHotSegments.
type GetHotSegmentsParams struct {
	// range.start (optional)
	RangeStart *string `form:"range.start" json:"range.start"`
	// range.end (optional)
	RangeEnd *string `form:"range.end" json:"range.end"`
}

// GetVideoHeatmap makes a GET request to /analytics/v1/videos/{video_id}/heatmap
// GetVideoHeatmap
func (c *Client) GetVideoHeatmap(ctx context.Context, videoId string, params *GetVideoHeatmapParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVideoHeatmapRequest(c.Server, videoId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHotSegments makes a GET request to /analytics/v1/videos/{video_id}/hot-segments
// GetHotSegments
func (c *Client) GetHotSegments(ctx context.Context, videoId string, params *GetHotSegmentsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHotSegmentsRequest(c.Server, videoId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetVideoHeatmapRequest creates a GET request for /analytics/v1/videos/{video_id}/heatmap
func NewGetVideoHeatmapRequest(server string, videoId string, params *GetVideoHeatmapParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("video_id", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/analytics/v1/videos/%s/heatmap", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.Buckets != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("buckets", *params.Buckets, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "integer", Format: "int32", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.RangeStart != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("range.start", *params.RangeStart, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.RangeEnd != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("range.end", *params.RangeEnd, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHotSegmentsRequest creates a GET request for /analytics/v1/videos/{video_id}/hot-segments
func NewGetHotSegmentsRequest(server string, videoId string, params *GetHotSegmentsParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("video_id", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/analytics/v1/videos/%s/hot-segments", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.RangeStart != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("range.start", *params.RangeStart, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.RangeEnd != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("range.end", *params.RangeEnd, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// ClientHttpError represents an HTTP error response.
// The type parameter E is the type of the parsed error body.
type ClientHttpError[E any] struct {
	StatusCode int
	Body       E
	RawBody    []byte
}

func (e *ClientHttpError[E]) Error() string {
	return fmt.Sprintf("HTTP %d", e.StatusCode)
}

// SimpleClient wraps Client with typed responses for operations that have
// unambiguous response types. Methods return the success type directly,
// and HTTP errors are returned as *ClientHttpError[E] where E is the error type.
type SimpleClient struct {
	*Client
}

// NewSimpleClient creates a new SimpleClient which wraps a Client.
func NewSimpleClient(server string, opts ...ClientOption) (*SimpleClient, error) {
	inner, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &SimpleClient{Client: inner}, nil
}

// GetVideoHeatmap makes a GET request to /analytics/v1/videos/{video_id}/heatmap and returns the parsed response.
// GetVideoHeatmap
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetVideoHeatmap(ctx context.Context, videoId string, params *GetVideoHeatmapParams, reqEditors ...RequestEditorFn) (models.AnalyticsV1VideoHeatmap, error) {
	var result models.AnalyticsV1VideoHeatmap
	resp, err := c.Client.GetVideoHeatmap(ctx, videoId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// GetHotSegments makes a GET request to /analytics/v1/videos/{video_id}/hot-segments and returns the parsed response.
// GetHotSegments
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetHotSegments(ctx context.Context, videoId string, params *GetHotSegmentsParams, reqEditors ...RequestEditorFn) (models.AnalyticsV1HotSegmentsResponse, error) {
	var result models.AnalyticsV1HotSegmentsResponse
	resp, err := c.Client.GetHotSegments(ctx, videoId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}
