// Code generated by oapi-codegen; DO NOT EDIT.

package passkeys

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/rixlhq/rixl-go/sdk/models"
	oapiCodegenParamsPkg "github.com/rixlhq/rixl-go/sdk/runtime/params"
)

type PasskeyLoginBeginJSONRequestBody = models.AuthV1PasskeyLoginBeginRequest

type PasskeyLoginFinishJSONRequestBody = models.AuthV1PasskeyLoginFinishRequest

type PasskeyRegisterBeginJSONRequestBody = models.AuthV1PasskeyRegisterBeginRequest

type PasskeyRegisterFinishJSONRequestBody = models.AuthV1PasskeyRegisterFinishRequest

type RenamePasskeyJSONRequestBody = any

type VerifyPasskeyForLoginJSONRequestBody = models.AuthV1VerifyPasskeyForLoginRequest

// RequestEditorFn is the function signature for the RequestEditor callback function.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the OpenAPI spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction.
type ClientOption func(*Client) error

// NewClient creates a new Client with reasonable defaults.
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// Ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// Create httpClient if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientInterface is the interface specification for the client.
type ClientInterface interface {
	// PasskeyLoginBeginWithBody makes a POST request to /auth/v1/passkey/login/begin
	PasskeyLoginBeginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	PasskeyLoginBegin(ctx context.Context, body PasskeyLoginBeginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// PasskeyLoginFinishWithBody makes a POST request to /auth/v1/passkey/login/finish
	PasskeyLoginFinishWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	PasskeyLoginFinish(ctx context.Context, body PasskeyLoginFinishJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ListPasskeys makes a GET request to /auth/v1/users/current/passkeys
	ListPasskeys(ctx context.Context, params *ListPasskeysParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// PasskeyRegisterBeginWithBody makes a POST request to /auth/v1/users/current/passkeys/register/begin
	PasskeyRegisterBeginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	PasskeyRegisterBegin(ctx context.Context, body PasskeyRegisterBeginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// PasskeyRegisterFinishWithBody makes a POST request to /auth/v1/users/current/passkeys/register/finish
	PasskeyRegisterFinishWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	PasskeyRegisterFinish(ctx context.Context, body PasskeyRegisterFinishJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// DeletePasskey makes a DELETE request to /auth/v1/users/current/passkeys/{id}
	DeletePasskey(ctx context.Context, id string, params *DeletePasskeyParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// RenamePasskeyWithBody makes a PATCH request to /auth/v1/users/current/passkeys/{id}
	RenamePasskeyWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	RenamePasskey(ctx context.Context, id string, body RenamePasskeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// VerifyPasskeyForLoginWithBody makes a POST request to /auth/v1/verify-passkey
	VerifyPasskeyForLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	VerifyPasskeyForLogin(ctx context.Context, body VerifyPasskeyForLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListPasskeysParams defines parameters for ListPasskeys.
type ListPasskeysParams struct {
	// user_id (optional)
	UserId *string `form:"user_id" json:"user_id"`
}

// DeletePasskeyParams defines parameters for DeletePasskey.
type DeletePasskeyParams struct {
	// user_id (optional)
	UserId *string `form:"user_id" json:"user_id"`
}

// PasskeyLoginBeginWithBody makes a POST request to /auth/v1/passkey/login/begin
// PasskeyLoginBegin
func (c *Client) PasskeyLoginBeginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPasskeyLoginBeginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PasskeyLoginBegin makes a POST request to /auth/v1/passkey/login/begin with application/json body
func (c *Client) PasskeyLoginBegin(ctx context.Context, body PasskeyLoginBeginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPasskeyLoginBeginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PasskeyLoginFinishWithBody makes a POST request to /auth/v1/passkey/login/finish
// PasskeyLoginFinish
func (c *Client) PasskeyLoginFinishWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPasskeyLoginFinishRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PasskeyLoginFinish makes a POST request to /auth/v1/passkey/login/finish with application/json body
func (c *Client) PasskeyLoginFinish(ctx context.Context, body PasskeyLoginFinishJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPasskeyLoginFinishRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListPasskeys makes a GET request to /auth/v1/users/current/passkeys
// ListPasskeys
func (c *Client) ListPasskeys(ctx context.Context, params *ListPasskeysParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPasskeysRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PasskeyRegisterBeginWithBody makes a POST request to /auth/v1/users/current/passkeys/register/begin
// PasskeyRegisterBegin
func (c *Client) PasskeyRegisterBeginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPasskeyRegisterBeginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PasskeyRegisterBegin makes a POST request to /auth/v1/users/current/passkeys/register/begin with application/json body
func (c *Client) PasskeyRegisterBegin(ctx context.Context, body PasskeyRegisterBeginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPasskeyRegisterBeginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PasskeyRegisterFinishWithBody makes a POST request to /auth/v1/users/current/passkeys/register/finish
// PasskeyRegisterFinish
func (c *Client) PasskeyRegisterFinishWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPasskeyRegisterFinishRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PasskeyRegisterFinish makes a POST request to /auth/v1/users/current/passkeys/register/finish with application/json body
func (c *Client) PasskeyRegisterFinish(ctx context.Context, body PasskeyRegisterFinishJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPasskeyRegisterFinishRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeletePasskey makes a DELETE request to /auth/v1/users/current/passkeys/{id}
// DeletePasskey
func (c *Client) DeletePasskey(ctx context.Context, id string, params *DeletePasskeyParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeletePasskeyRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RenamePasskeyWithBody makes a PATCH request to /auth/v1/users/current/passkeys/{id}
// RenamePasskey
func (c *Client) RenamePasskeyWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRenamePasskeyRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RenamePasskey makes a PATCH request to /auth/v1/users/current/passkeys/{id} with application/json body
func (c *Client) RenamePasskey(ctx context.Context, id string, body RenamePasskeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRenamePasskeyRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// VerifyPasskeyForLoginWithBody makes a POST request to /auth/v1/verify-passkey
// VerifyPasskeyForLogin
func (c *Client) VerifyPasskeyForLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVerifyPasskeyForLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// VerifyPasskeyForLogin makes a POST request to /auth/v1/verify-passkey with application/json body
func (c *Client) VerifyPasskeyForLogin(ctx context.Context, body VerifyPasskeyForLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVerifyPasskeyForLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPasskeyLoginBeginRequest creates a POST request for /auth/v1/passkey/login/begin with application/json body
func NewPasskeyLoginBeginRequest(server string, body PasskeyLoginBeginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPasskeyLoginBeginRequestWithBody(server, "application/json", bodyReader)
}

// NewPasskeyLoginBeginRequestWithBody creates a POST request for /auth/v1/passkey/login/begin with any body
func NewPasskeyLoginBeginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/passkey/login/begin")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPasskeyLoginFinishRequest creates a POST request for /auth/v1/passkey/login/finish with application/json body
func NewPasskeyLoginFinishRequest(server string, body PasskeyLoginFinishJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPasskeyLoginFinishRequestWithBody(server, "application/json", bodyReader)
}

// NewPasskeyLoginFinishRequestWithBody creates a POST request for /auth/v1/passkey/login/finish with any body
func NewPasskeyLoginFinishRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/passkey/login/finish")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListPasskeysRequest creates a GET request for /auth/v1/users/current/passkeys
func NewListPasskeysRequest(server string, params *ListPasskeysParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/users/current/passkeys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user_id", *params.UserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPasskeyRegisterBeginRequest creates a POST request for /auth/v1/users/current/passkeys/register/begin with application/json body
func NewPasskeyRegisterBeginRequest(server string, body PasskeyRegisterBeginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPasskeyRegisterBeginRequestWithBody(server, "application/json", bodyReader)
}

// NewPasskeyRegisterBeginRequestWithBody creates a POST request for /auth/v1/users/current/passkeys/register/begin with any body
func NewPasskeyRegisterBeginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/users/current/passkeys/register/begin")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPasskeyRegisterFinishRequest creates a POST request for /auth/v1/users/current/passkeys/register/finish with application/json body
func NewPasskeyRegisterFinishRequest(server string, body PasskeyRegisterFinishJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPasskeyRegisterFinishRequestWithBody(server, "application/json", bodyReader)
}

// NewPasskeyRegisterFinishRequestWithBody creates a POST request for /auth/v1/users/current/passkeys/register/finish with any body
func NewPasskeyRegisterFinishRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/users/current/passkeys/register/finish")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeletePasskeyRequest creates a DELETE request for /auth/v1/users/current/passkeys/{id}
func NewDeletePasskeyRequest(server string, id string, params *DeletePasskeyParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("id", id, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/users/current/passkeys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user_id", *params.UserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRenamePasskeyRequest creates a PATCH request for /auth/v1/users/current/passkeys/{id} with application/json body
func NewRenamePasskeyRequest(server string, id string, body RenamePasskeyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRenamePasskeyRequestWithBody(server, id, "application/json", bodyReader)
}

// NewRenamePasskeyRequestWithBody creates a PATCH request for /auth/v1/users/current/passkeys/{id} with any body
func NewRenamePasskeyRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("id", id, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/users/current/passkeys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewVerifyPasskeyForLoginRequest creates a POST request for /auth/v1/verify-passkey with application/json body
func NewVerifyPasskeyForLoginRequest(server string, body VerifyPasskeyForLoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewVerifyPasskeyForLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewVerifyPasskeyForLoginRequestWithBody creates a POST request for /auth/v1/verify-passkey with any body
func NewVerifyPasskeyForLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/verify-passkey")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// ClientHttpError represents an HTTP error response.
// The type parameter E is the type of the parsed error body.
type ClientHttpError[E any] struct {
	StatusCode int
	Body       E
	RawBody    []byte
}

func (e *ClientHttpError[E]) Error() string {
	return fmt.Sprintf("HTTP %d", e.StatusCode)
}

// SimpleClient wraps Client with typed responses for operations that have
// unambiguous response types. Methods return the success type directly,
// and HTTP errors are returned as *ClientHttpError[E] where E is the error type.
type SimpleClient struct {
	*Client
}

// NewSimpleClient creates a new SimpleClient which wraps a Client.
func NewSimpleClient(server string, opts ...ClientOption) (*SimpleClient, error) {
	inner, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &SimpleClient{Client: inner}, nil
}

// PasskeyLoginBegin makes a POST request to /auth/v1/passkey/login/begin and returns the parsed response.
// PasskeyLoginBegin
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) PasskeyLoginBegin(ctx context.Context, body PasskeyLoginBeginJSONRequestBody, reqEditors ...RequestEditorFn) (models.AuthV1PasskeyBeginResponse, error) {
	var result models.AuthV1PasskeyBeginResponse
	resp, err := c.Client.PasskeyLoginBegin(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// PasskeyLoginFinish makes a POST request to /auth/v1/passkey/login/finish and returns the parsed response.
// PasskeyLoginFinish
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) PasskeyLoginFinish(ctx context.Context, body PasskeyLoginFinishJSONRequestBody, reqEditors ...RequestEditorFn) (models.AuthV1TokenResponse, error) {
	var result models.AuthV1TokenResponse
	resp, err := c.Client.PasskeyLoginFinish(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// ListPasskeys makes a GET request to /auth/v1/users/current/passkeys and returns the parsed response.
// ListPasskeys
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) ListPasskeys(ctx context.Context, params *ListPasskeysParams, reqEditors ...RequestEditorFn) (models.AuthV1ListPasskeysResponse, error) {
	var result models.AuthV1ListPasskeysResponse
	resp, err := c.Client.ListPasskeys(ctx, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// PasskeyRegisterBegin makes a POST request to /auth/v1/users/current/passkeys/register/begin and returns the parsed response.
// PasskeyRegisterBegin
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) PasskeyRegisterBegin(ctx context.Context, body PasskeyRegisterBeginJSONRequestBody, reqEditors ...RequestEditorFn) (models.AuthV1PasskeyBeginResponse, error) {
	var result models.AuthV1PasskeyBeginResponse
	resp, err := c.Client.PasskeyRegisterBegin(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// PasskeyRegisterFinish makes a POST request to /auth/v1/users/current/passkeys/register/finish and returns the parsed response.
// PasskeyRegisterFinish
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) PasskeyRegisterFinish(ctx context.Context, body PasskeyRegisterFinishJSONRequestBody, reqEditors ...RequestEditorFn) (models.AuthV1PasskeyRegisterFinishResponse, error) {
	var result models.AuthV1PasskeyRegisterFinishResponse
	resp, err := c.Client.PasskeyRegisterFinish(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// DeletePasskey makes a DELETE request to /auth/v1/users/current/passkeys/{id} and returns the parsed response.
// DeletePasskey
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) DeletePasskey(ctx context.Context, id string, params *DeletePasskeyParams, reqEditors ...RequestEditorFn) (models.GoogleProtobufEmpty, error) {
	var result models.GoogleProtobufEmpty
	resp, err := c.Client.DeletePasskey(ctx, id, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// RenamePasskey makes a PATCH request to /auth/v1/users/current/passkeys/{id} and returns the parsed response.
// RenamePasskey
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) RenamePasskey(ctx context.Context, id string, body RenamePasskeyJSONRequestBody, reqEditors ...RequestEditorFn) (models.GoogleProtobufEmpty, error) {
	var result models.GoogleProtobufEmpty
	resp, err := c.Client.RenamePasskey(ctx, id, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// VerifyPasskeyForLogin makes a POST request to /auth/v1/verify-passkey and returns the parsed response.
// VerifyPasskeyForLogin
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) VerifyPasskeyForLogin(ctx context.Context, body VerifyPasskeyForLoginJSONRequestBody, reqEditors ...RequestEditorFn) (models.AuthV1TokenResponse, error) {
	var result models.AuthV1TokenResponse
	resp, err := c.Client.VerifyPasskeyForLogin(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}
