// Code generated by oapi-codegen; DO NOT EDIT.

package usage

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/rixlhq/rixl-go/sdk/models"
	oapiCodegenParamsPkg "github.com/rixlhq/rixl-go/sdk/runtime/params"
)

// RequestEditorFn is the function signature for the RequestEditor callback function.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the OpenAPI spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction.
type ClientOption func(*Client) error

// NewClient creates a new Client with reasonable defaults.
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// Ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// Create httpClient if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientInterface is the interface specification for the client.
type ClientInterface interface {
	// GetBandwidthUsage makes a GET request to /billing/v1/bandwidth-usage
	GetBandwidthUsage(ctx context.Context, params *GetBandwidthUsageParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetBandwidthUsageHistory makes a GET request to /billing/v1/bandwidth-usage/history
	GetBandwidthUsageHistory(ctx context.Context, params *GetBandwidthUsageHistoryParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// RefreshBandwidthUsage makes a POST request to /billing/v1/bandwidth-usage/refresh
	RefreshBandwidthUsage(ctx context.Context, params *RefreshBandwidthUsageParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetStorageUsage makes a GET request to /billing/v1/storage-usage
	GetStorageUsage(ctx context.Context, params *GetStorageUsageParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetStorageUsageHistory makes a GET request to /billing/v1/storage-usage/history
	GetStorageUsageHistory(ctx context.Context, params *GetStorageUsageHistoryParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// RefreshStorageUsage makes a POST request to /billing/v1/storage-usage/refresh
	RefreshStorageUsage(ctx context.Context, params *RefreshStorageUsageParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetBandwidthUsageParams defines parameters for GetBandwidthUsage.
type GetBandwidthUsageParams struct {
	// org_id (optional)
	OrgId *string `form:"org_id" json:"org_id"`
}

// GetBandwidthUsageHistoryParams defines parameters for GetBandwidthUsageHistory.
type GetBandwidthUsageHistoryParams struct {
	// org_id (optional)
	OrgId *string `form:"org_id" json:"org_id"`
	// days (optional)
	Days *int32 `form:"days" json:"days"`
}

// RefreshBandwidthUsageParams defines parameters for RefreshBandwidthUsage.
type RefreshBandwidthUsageParams struct {
	// org_id (optional)
	OrgId *string `form:"org_id" json:"org_id"`
}

// GetStorageUsageParams defines parameters for GetStorageUsage.
type GetStorageUsageParams struct {
	// org_id (optional)
	OrgId *string `form:"org_id" json:"org_id"`
}

// GetStorageUsageHistoryParams defines parameters for GetStorageUsageHistory.
type GetStorageUsageHistoryParams struct {
	// org_id (optional)
	OrgId *string `form:"org_id" json:"org_id"`
	// days (optional)
	Days *int32 `form:"days" json:"days"`
}

// RefreshStorageUsageParams defines parameters for RefreshStorageUsage.
type RefreshStorageUsageParams struct {
	// org_id (optional)
	OrgId *string `form:"org_id" json:"org_id"`
}

// GetBandwidthUsage makes a GET request to /billing/v1/bandwidth-usage
// GetBandwidthUsage
func (c *Client) GetBandwidthUsage(ctx context.Context, params *GetBandwidthUsageParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBandwidthUsageRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetBandwidthUsageHistory makes a GET request to /billing/v1/bandwidth-usage/history
// GetBandwidthUsageHistory
func (c *Client) GetBandwidthUsageHistory(ctx context.Context, params *GetBandwidthUsageHistoryParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBandwidthUsageHistoryRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RefreshBandwidthUsage makes a POST request to /billing/v1/bandwidth-usage/refresh
// RefreshBandwidthUsage
func (c *Client) RefreshBandwidthUsage(ctx context.Context, params *RefreshBandwidthUsageParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRefreshBandwidthUsageRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetStorageUsage makes a GET request to /billing/v1/storage-usage
// GetStorageUsage
func (c *Client) GetStorageUsage(ctx context.Context, params *GetStorageUsageParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStorageUsageRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetStorageUsageHistory makes a GET request to /billing/v1/storage-usage/history
// GetStorageUsageHistory
func (c *Client) GetStorageUsageHistory(ctx context.Context, params *GetStorageUsageHistoryParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStorageUsageHistoryRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RefreshStorageUsage makes a POST request to /billing/v1/storage-usage/refresh
// RefreshStorageUsage
func (c *Client) RefreshStorageUsage(ctx context.Context, params *RefreshStorageUsageParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRefreshStorageUsageRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetBandwidthUsageRequest creates a GET request for /billing/v1/bandwidth-usage
func NewGetBandwidthUsageRequest(server string, params *GetBandwidthUsageParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/billing/v1/bandwidth-usage")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.OrgId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("org_id", *params.OrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBandwidthUsageHistoryRequest creates a GET request for /billing/v1/bandwidth-usage/history
func NewGetBandwidthUsageHistoryRequest(server string, params *GetBandwidthUsageHistoryParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/billing/v1/bandwidth-usage/history")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.OrgId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("org_id", *params.OrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Days != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("days", *params.Days, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "integer", Format: "int32", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRefreshBandwidthUsageRequest creates a POST request for /billing/v1/bandwidth-usage/refresh
func NewRefreshBandwidthUsageRequest(server string, params *RefreshBandwidthUsageParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/billing/v1/bandwidth-usage/refresh")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.OrgId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("org_id", *params.OrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetStorageUsageRequest creates a GET request for /billing/v1/storage-usage
func NewGetStorageUsageRequest(server string, params *GetStorageUsageParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/billing/v1/storage-usage")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.OrgId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("org_id", *params.OrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetStorageUsageHistoryRequest creates a GET request for /billing/v1/storage-usage/history
func NewGetStorageUsageHistoryRequest(server string, params *GetStorageUsageHistoryParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/billing/v1/storage-usage/history")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.OrgId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("org_id", *params.OrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Days != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("days", *params.Days, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "integer", Format: "int32", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRefreshStorageUsageRequest creates a POST request for /billing/v1/storage-usage/refresh
func NewRefreshStorageUsageRequest(server string, params *RefreshStorageUsageParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/billing/v1/storage-usage/refresh")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.OrgId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("org_id", *params.OrgId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// ClientHttpError represents an HTTP error response.
// The type parameter E is the type of the parsed error body.
type ClientHttpError[E any] struct {
	StatusCode int
	Body       E
	RawBody    []byte
}

func (e *ClientHttpError[E]) Error() string {
	return fmt.Sprintf("HTTP %d", e.StatusCode)
}

// SimpleClient wraps Client with typed responses for operations that have
// unambiguous response types. Methods return the success type directly,
// and HTTP errors are returned as *ClientHttpError[E] where E is the error type.
type SimpleClient struct {
	*Client
}

// NewSimpleClient creates a new SimpleClient which wraps a Client.
func NewSimpleClient(server string, opts ...ClientOption) (*SimpleClient, error) {
	inner, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &SimpleClient{Client: inner}, nil
}

// GetBandwidthUsage makes a GET request to /billing/v1/bandwidth-usage and returns the parsed response.
// GetBandwidthUsage
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetBandwidthUsage(ctx context.Context, params *GetBandwidthUsageParams, reqEditors ...RequestEditorFn) (models.BillingV1BandwidthUsage, error) {
	var result models.BillingV1BandwidthUsage
	resp, err := c.Client.GetBandwidthUsage(ctx, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// GetBandwidthUsageHistory makes a GET request to /billing/v1/bandwidth-usage/history and returns the parsed response.
// GetBandwidthUsageHistory
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetBandwidthUsageHistory(ctx context.Context, params *GetBandwidthUsageHistoryParams, reqEditors ...RequestEditorFn) (models.BillingV1GetBandwidthUsageHistoryResponse, error) {
	var result models.BillingV1GetBandwidthUsageHistoryResponse
	resp, err := c.Client.GetBandwidthUsageHistory(ctx, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// RefreshBandwidthUsage makes a POST request to /billing/v1/bandwidth-usage/refresh and returns the parsed response.
// RefreshBandwidthUsage
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) RefreshBandwidthUsage(ctx context.Context, params *RefreshBandwidthUsageParams, reqEditors ...RequestEditorFn) (models.BillingV1BandwidthUsage, error) {
	var result models.BillingV1BandwidthUsage
	resp, err := c.Client.RefreshBandwidthUsage(ctx, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// GetStorageUsage makes a GET request to /billing/v1/storage-usage and returns the parsed response.
// GetStorageUsage
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetStorageUsage(ctx context.Context, params *GetStorageUsageParams, reqEditors ...RequestEditorFn) (models.BillingV1StorageUsage, error) {
	var result models.BillingV1StorageUsage
	resp, err := c.Client.GetStorageUsage(ctx, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// GetStorageUsageHistory makes a GET request to /billing/v1/storage-usage/history and returns the parsed response.
// GetStorageUsageHistory
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetStorageUsageHistory(ctx context.Context, params *GetStorageUsageHistoryParams, reqEditors ...RequestEditorFn) (models.BillingV1GetStorageUsageHistoryResponse, error) {
	var result models.BillingV1GetStorageUsageHistoryResponse
	resp, err := c.Client.GetStorageUsageHistory(ctx, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// RefreshStorageUsage makes a POST request to /billing/v1/storage-usage/refresh and returns the parsed response.
// RefreshStorageUsage
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) RefreshStorageUsage(ctx context.Context, params *RefreshStorageUsageParams, reqEditors ...RequestEditorFn) (models.BillingV1StorageUsage, error) {
	var result models.BillingV1StorageUsage
	resp, err := c.Client.RefreshStorageUsage(ctx, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}
