// Code generated by oapi-codegen; DO NOT EDIT.

package blog

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/rixlhq/rixl-go/sdk/models"
	oapiCodegenParamsPkg "github.com/rixlhq/rixl-go/sdk/runtime/params"
)

type SendBlogBroadcastJSONRequestBody = models.AuthV1SendBlogBroadcastRequest

type UnsubscribeBlogByEmailJSONRequestBody = models.AuthV1UnsubscribeBlogByEmailRequest

// RequestEditorFn is the function signature for the RequestEditor callback function.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the OpenAPI spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction.
type ClientOption func(*Client) error

// NewClient creates a new Client with reasonable defaults.
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// Ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// Create httpClient if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientInterface is the interface specification for the client.
type ClientInterface interface {
	// SendBlogBroadcastWithBody makes a POST request to /auth/v1/blog/broadcast
	SendBlogBroadcastWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	SendBlogBroadcast(ctx context.Context, body SendBlogBroadcastJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// SubscribeBlog makes a POST request to /auth/v1/blog/subscribe
	SubscribeBlog(ctx context.Context, params *SubscribeBlogParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetBlogSubscription makes a GET request to /auth/v1/blog/subscription
	GetBlogSubscription(ctx context.Context, params *GetBlogSubscriptionParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// UnsubscribeBlog makes a POST request to /auth/v1/blog/unsubscribe
	UnsubscribeBlog(ctx context.Context, params *UnsubscribeBlogParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// UnsubscribeBlogByEmailWithBody makes a POST request to /auth/v1/blog/unsubscribe/email
	UnsubscribeBlogByEmailWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	UnsubscribeBlogByEmail(ctx context.Context, body UnsubscribeBlogByEmailJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// SubscribeBlogParams defines parameters for SubscribeBlog.
type SubscribeBlogParams struct {
	// user_id (optional)
	UserId *string `form:"user_id" json:"user_id"`
}

// GetBlogSubscriptionParams defines parameters for GetBlogSubscription.
type GetBlogSubscriptionParams struct {
	// user_id (optional)
	UserId *string `form:"user_id" json:"user_id"`
}

// UnsubscribeBlogParams defines parameters for UnsubscribeBlog.
type UnsubscribeBlogParams struct {
	// user_id (optional)
	UserId *string `form:"user_id" json:"user_id"`
}

// SendBlogBroadcastWithBody makes a POST request to /auth/v1/blog/broadcast
// SendBlogBroadcast
func (c *Client) SendBlogBroadcastWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendBlogBroadcastRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SendBlogBroadcast makes a POST request to /auth/v1/blog/broadcast with application/json body
func (c *Client) SendBlogBroadcast(ctx context.Context, body SendBlogBroadcastJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendBlogBroadcastRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SubscribeBlog makes a POST request to /auth/v1/blog/subscribe
// SubscribeBlog
func (c *Client) SubscribeBlog(ctx context.Context, params *SubscribeBlogParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubscribeBlogRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetBlogSubscription makes a GET request to /auth/v1/blog/subscription
// GetBlogSubscription
func (c *Client) GetBlogSubscription(ctx context.Context, params *GetBlogSubscriptionParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBlogSubscriptionRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UnsubscribeBlog makes a POST request to /auth/v1/blog/unsubscribe
// UnsubscribeBlog
func (c *Client) UnsubscribeBlog(ctx context.Context, params *UnsubscribeBlogParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUnsubscribeBlogRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UnsubscribeBlogByEmailWithBody makes a POST request to /auth/v1/blog/unsubscribe/email
// UnsubscribeBlogByEmail
func (c *Client) UnsubscribeBlogByEmailWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUnsubscribeBlogByEmailRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UnsubscribeBlogByEmail makes a POST request to /auth/v1/blog/unsubscribe/email with application/json body
func (c *Client) UnsubscribeBlogByEmail(ctx context.Context, body UnsubscribeBlogByEmailJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUnsubscribeBlogByEmailRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSendBlogBroadcastRequest creates a POST request for /auth/v1/blog/broadcast with application/json body
func NewSendBlogBroadcastRequest(server string, body SendBlogBroadcastJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendBlogBroadcastRequestWithBody(server, "application/json", bodyReader)
}

// NewSendBlogBroadcastRequestWithBody creates a POST request for /auth/v1/blog/broadcast with any body
func NewSendBlogBroadcastRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/blog/broadcast")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSubscribeBlogRequest creates a POST request for /auth/v1/blog/subscribe
func NewSubscribeBlogRequest(server string, params *SubscribeBlogParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/blog/subscribe")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user_id", *params.UserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBlogSubscriptionRequest creates a GET request for /auth/v1/blog/subscription
func NewGetBlogSubscriptionRequest(server string, params *GetBlogSubscriptionParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/blog/subscription")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user_id", *params.UserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUnsubscribeBlogRequest creates a POST request for /auth/v1/blog/unsubscribe
func NewUnsubscribeBlogRequest(server string, params *UnsubscribeBlogParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/blog/unsubscribe")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.UserId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("user_id", *params.UserId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUnsubscribeBlogByEmailRequest creates a POST request for /auth/v1/blog/unsubscribe/email with application/json body
func NewUnsubscribeBlogByEmailRequest(server string, body UnsubscribeBlogByEmailJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUnsubscribeBlogByEmailRequestWithBody(server, "application/json", bodyReader)
}

// NewUnsubscribeBlogByEmailRequestWithBody creates a POST request for /auth/v1/blog/unsubscribe/email with any body
func NewUnsubscribeBlogByEmailRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/v1/blog/unsubscribe/email")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// ClientHttpError represents an HTTP error response.
// The type parameter E is the type of the parsed error body.
type ClientHttpError[E any] struct {
	StatusCode int
	Body       E
	RawBody    []byte
}

func (e *ClientHttpError[E]) Error() string {
	return fmt.Sprintf("HTTP %d", e.StatusCode)
}

// SimpleClient wraps Client with typed responses for operations that have
// unambiguous response types. Methods return the success type directly,
// and HTTP errors are returned as *ClientHttpError[E] where E is the error type.
type SimpleClient struct {
	*Client
}

// NewSimpleClient creates a new SimpleClient which wraps a Client.
func NewSimpleClient(server string, opts ...ClientOption) (*SimpleClient, error) {
	inner, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &SimpleClient{Client: inner}, nil
}

// SendBlogBroadcast makes a POST request to /auth/v1/blog/broadcast and returns the parsed response.
// SendBlogBroadcast
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) SendBlogBroadcast(ctx context.Context, body SendBlogBroadcastJSONRequestBody, reqEditors ...RequestEditorFn) (models.AuthV1SendBlogBroadcastResponse, error) {
	var result models.AuthV1SendBlogBroadcastResponse
	resp, err := c.Client.SendBlogBroadcast(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// SubscribeBlog makes a POST request to /auth/v1/blog/subscribe and returns the parsed response.
// SubscribeBlog
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) SubscribeBlog(ctx context.Context, params *SubscribeBlogParams, reqEditors ...RequestEditorFn) (models.GoogleProtobufEmpty, error) {
	var result models.GoogleProtobufEmpty
	resp, err := c.Client.SubscribeBlog(ctx, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// GetBlogSubscription makes a GET request to /auth/v1/blog/subscription and returns the parsed response.
// GetBlogSubscription
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetBlogSubscription(ctx context.Context, params *GetBlogSubscriptionParams, reqEditors ...RequestEditorFn) (models.AuthV1BlogSubscriptionResponse, error) {
	var result models.AuthV1BlogSubscriptionResponse
	resp, err := c.Client.GetBlogSubscription(ctx, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// UnsubscribeBlog makes a POST request to /auth/v1/blog/unsubscribe and returns the parsed response.
// UnsubscribeBlog
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) UnsubscribeBlog(ctx context.Context, params *UnsubscribeBlogParams, reqEditors ...RequestEditorFn) (models.GoogleProtobufEmpty, error) {
	var result models.GoogleProtobufEmpty
	resp, err := c.Client.UnsubscribeBlog(ctx, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// UnsubscribeBlogByEmail makes a POST request to /auth/v1/blog/unsubscribe/email and returns the parsed response.
// UnsubscribeBlogByEmail
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) UnsubscribeBlogByEmail(ctx context.Context, body UnsubscribeBlogByEmailJSONRequestBody, reqEditors ...RequestEditorFn) (models.GoogleProtobufEmpty, error) {
	var result models.GoogleProtobufEmpty
	resp, err := c.Client.UnsubscribeBlogByEmail(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}
