// Code generated by oapi-codegen; DO NOT EDIT.

package models

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"
	"sync"
)

// #/components/schemas/AudioTrack
type AudioTrack struct {
	CreatedAt    *string `form:"created_at,omitempty" json:"created_at,omitempty"`
	Format       *string `form:"format,omitempty" json:"format,omitempty"`
	ID           *string `form:"id,omitempty" json:"id,omitempty"`
	Label        *string `form:"label,omitempty" json:"label,omitempty"`
	LanguageCode *string `form:"language_code,omitempty" json:"language_code,omitempty"`
	Name         *string `form:"name,omitempty" json:"name,omitempty"`
	Size         *int    `form:"size,omitempty" json:"size,omitempty"`
	URL          *string `form:"url,omitempty" json:"url,omitempty"`
	VideoID      *string `form:"video_id,omitempty" json:"video_id,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AudioTrack) ApplyDefaults() {
}

// #/components/schemas/AudioTrackDelete
type AudioTrackDelete struct {
	Message *string `form:"message,omitempty" json:"message,omitempty"`
	Status  *string `form:"status,omitempty" json:"status,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AudioTrackDelete) ApplyDefaults() {
}

// #/components/schemas/Chapter
type Chapter struct {
	DurationLabel *string  `form:"duration_label,omitempty" json:"duration_label,omitempty"`
	EndTimeSec    *float32 `form:"end_time_sec,omitempty" json:"end_time_sec,omitempty"`
	StartTimeSec  *float32 `form:"start_time_sec,omitempty" json:"start_time_sec,omitempty"`
	Title         *string  `form:"title,omitempty" json:"title,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Chapter) ApplyDefaults() {
}

// #/components/schemas/File
type File struct {
	CreatedAt *string     `form:"created_at,omitempty" json:"created_at,omitempty"`
	Format    *string     `form:"format,omitempty" json:"format,omitempty"`
	ID        *string     `form:"id,omitempty" json:"id,omitempty"`
	Name      *string     `form:"name,omitempty" json:"name,omitempty"`
	ProjectID *string     `form:"project_id,omitempty" json:"project_id,omitempty"`
	Size      *int        `form:"size,omitempty" json:"size,omitempty"`
	Status    *FileStatus `form:"status,omitempty" json:"status,omitempty"`
	UpdatedAt *string     `form:"updated_at,omitempty" json:"updated_at,omitempty"`
	URL       *string     `form:"url,omitempty" json:"url,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *File) ApplyDefaults() {
}

// #/components/schemas/FileStatus
type FileStatus string

const (
	FileStatusUploading  FileStatus = "uploading"
	FileStatusUploaded   FileStatus = "uploaded"
	FileStatusProcessing FileStatus = "processing"
	FileStatusPreparing  FileStatus = "preparing"
	FileStatusReady      FileStatus = "ready"
	FileStatusError      FileStatus = "error"
)

// #/components/schemas/Image
type Image struct {
	AttachedToVideo *bool   `form:"attached_to_video,omitempty" json:"attached_to_video,omitempty"`
	File            *File   `form:"file,omitempty" json:"file,omitempty"`
	Height          *int    `form:"height,omitempty" json:"height,omitempty"`
	ID              *string `form:"id,omitempty" json:"id,omitempty"`
	Thumbhash       *string `form:"thumbhash,omitempty" json:"thumbhash,omitempty"`
	Width           *int    `form:"width,omitempty" json:"width,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Image) ApplyDefaults() {
	if s.File != nil {
		s.File.ApplyDefaults()
	}
}

// #/components/schemas/Post
type Post struct {
	CreatedAt   *string                                        `form:"created_at,omitempty" json:"created_at,omitempty"`
	CreatorID   *string                                        `form:"creator_id,omitempty" json:"creator_id,omitempty"`
	Description *string                                        `form:"description,omitempty" json:"description,omitempty"`
	FeedID      *string                                        `form:"feed_id,omitempty" json:"feed_id,omitempty"`
	ID          *string                                        `form:"id,omitempty" json:"id,omitempty"`
	Image       *Image                                         `form:"image,omitempty" json:"image,omitempty"`
	PlanType    *GithubComRixlhqAPIDBSqlcPlanType              `form:"plan_type,omitempty" json:"plan_type,omitempty"`
	Type        *PostType                                      `form:"type,omitempty" json:"type,omitempty"`
	UpdatedAt   *string                                        `form:"updated_at,omitempty" json:"updated_at,omitempty"`
	Video       *GithubComRixlhqAPIInternalVideosVideoResponse `form:"video,omitempty" json:"video,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Post) ApplyDefaults() {
	if s.Image != nil {
		s.Image.ApplyDefaults()
	}
	if s.Video != nil {
		s.Video.ApplyDefaults()
	}
}

// #/components/schemas/PostType
type PostType string

const (
	PostTypeImage PostType = "image"
	PostTypeVideo PostType = "video"
)

// #/components/schemas/Subtitle
type Subtitle struct {
	CreatedAt    *string `form:"created_at,omitempty" json:"created_at,omitempty"`
	ID           *string `form:"id,omitempty" json:"id,omitempty"`
	Label        *string `form:"label,omitempty" json:"label,omitempty"`
	LanguageCode *string `form:"language_code,omitempty" json:"language_code,omitempty"`
	Name         *string `form:"name,omitempty" json:"name,omitempty"`
	Size         *int    `form:"size,omitempty" json:"size,omitempty"`
	URL          *string `form:"url,omitempty" json:"url,omitempty"`
	VideoID      *string `form:"video_id,omitempty" json:"video_id,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Subtitle) ApplyDefaults() {
}

// #/components/schemas/SubtitleDelete
type SubtitleDelete struct {
	Message *string `form:"message,omitempty" json:"message,omitempty"`
	Status  *string `form:"status,omitempty" json:"status,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *SubtitleDelete) ApplyDefaults() {
}

// #/components/schemas/UpdateChaptersRequest
type UpdateChaptersRequest struct {
	Chapters []GithubComRixlhqAPIInternalVideosTypesChapterInput `form:"chapters,omitempty" json:"chapters,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *UpdateChaptersRequest) ApplyDefaults() {
}

// #/components/schemas/UpdateChaptersRequest/properties/chapters
type UpdateChaptersRequestChapters = []GithubComRixlhqAPIInternalVideosTypesChapterInput

// #/components/schemas/UpdateChaptersResponse
type UpdateChaptersResponse struct {
	Chapters []Chapter `form:"chapters,omitempty" json:"chapters,omitempty"`
	VideoID  *string   `form:"video_id,omitempty" json:"video_id,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *UpdateChaptersResponse) ApplyDefaults() {
}

// #/components/schemas/UpdateChaptersResponse/properties/chapters
type UpdateChaptersResponseChapters = []Chapter

// #/components/schemas/Video
type Video struct {
	Bitrate   *int                              `form:"bitrate,omitempty" json:"bitrate,omitempty"`
	Chapters  []Chapter                         `form:"chapters,omitempty" json:"chapters,omitempty"`
	Codec     *string                           `form:"codec,omitempty" json:"codec,omitempty"`
	Duration  *float32                          `form:"duration,omitempty" json:"duration,omitempty"`
	File      *File                             `form:"file,omitempty" json:"file,omitempty"`
	Framerate *string                           `form:"framerate,omitempty" json:"framerate,omitempty"`
	Hdr       *bool                             `form:"hdr,omitempty" json:"hdr,omitempty"`
	Height    *int                              `form:"height,omitempty" json:"height,omitempty"`
	ID        *string                           `form:"id,omitempty" json:"id,omitempty"`
	PlanType  *GithubComRixlhqAPIDBSqlcPlanType `form:"plan_type,omitempty" json:"plan_type,omitempty"`
	Poster    *Image                            `form:"poster,omitempty" json:"poster,omitempty"`
	Width     *int                              `form:"width,omitempty" json:"width,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Video) ApplyDefaults() {
	if s.File != nil {
		s.File.ApplyDefaults()
	}
	if s.Poster != nil {
		s.Poster.ApplyDefaults()
	}
}

// #/components/schemas/Video/properties/chapters
type VideoChapters = []Chapter

// #/components/schemas/VideoUploadInitRequest
type VideoUploadInitRequest struct {
	FileName     string                                `form:"file_name" json:"file_name"`
	ImageFormat  *string                               `form:"image_format,omitempty" json:"image_format,omitempty"`
	VideoQuality *GithubComRixlhqAPIDBSqlcVideoQuality `form:"video_quality,omitempty" json:"video_quality,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *VideoUploadInitRequest) ApplyDefaults() {
}

// #/components/schemas/github_com_rixlhq_api_db_sqlc.PlanType
type GithubComRixlhqAPIDBSqlcPlanType string

const (
	PlanTypeFree       GithubComRixlhqAPIDBSqlcPlanType = "free"
	PlanTypePro        GithubComRixlhqAPIDBSqlcPlanType = "pro"
	PlanTypeCustom     GithubComRixlhqAPIDBSqlcPlanType = "custom"
	PlanTypePayAsYouGo GithubComRixlhqAPIDBSqlcPlanType = "pay_as_you_go"
)

// #/components/schemas/github_com_rixlhq_api_db_sqlc.VideoQuality
type GithubComRixlhqAPIDBSqlcVideoQuality string

const (
	VideoQualityBasic  GithubComRixlhqAPIDBSqlcVideoQuality = "basic"
	VideoQualityShorts GithubComRixlhqAPIDBSqlcVideoQuality = "shorts"
	VideoQualityPro    GithubComRixlhqAPIDBSqlcVideoQuality = "pro"
)

// #/components/schemas/github_com_rixlhq_api_internal_errors.ErrorResponse
// Standard error response returned by the API
type GithubComRixlhqAPIInternalErrorsErrorResponse struct {
	// HTTP status code
	Code *int `form:"code,omitempty" json:"code,omitempty"`
	// Optional details about the error
	Details *string `form:"details,omitempty" json:"details,omitempty"`
	// Error message describing what went wrong
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GithubComRixlhqAPIInternalErrorsErrorResponse) ApplyDefaults() {
}

// #/components/schemas/github_com_rixlhq_api_internal_videos.VideoResponse
type GithubComRixlhqAPIInternalVideosVideoResponse struct {
	Bitrate   *int                              `form:"bitrate,omitempty" json:"bitrate,omitempty"`
	Chapters  []Chapter                         `form:"chapters,omitempty" json:"chapters,omitempty"`
	Codec     *string                           `form:"codec,omitempty" json:"codec,omitempty"`
	Duration  *float32                          `form:"duration,omitempty" json:"duration,omitempty"`
	File      *File                             `form:"file,omitempty" json:"file,omitempty"`
	Framerate *string                           `form:"framerate,omitempty" json:"framerate,omitempty"`
	Hdr       *bool                             `form:"hdr,omitempty" json:"hdr,omitempty"`
	Height    *int                              `form:"height,omitempty" json:"height,omitempty"`
	ID        *string                           `form:"id,omitempty" json:"id,omitempty"`
	PlanType  *GithubComRixlhqAPIDBSqlcPlanType `form:"plan_type,omitempty" json:"plan_type,omitempty"`
	Poster    *Image                            `form:"poster,omitempty" json:"poster,omitempty"`
	Width     *int                              `form:"width,omitempty" json:"width,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GithubComRixlhqAPIInternalVideosVideoResponse) ApplyDefaults() {
	if s.File != nil {
		s.File.ApplyDefaults()
	}
	if s.Poster != nil {
		s.Poster.ApplyDefaults()
	}
}

// #/components/schemas/github_com_rixlhq_api_internal_videos.VideoResponse/properties/chapters
type GithubComRixlhqAPIInternalVideosVideoResponseChapters = []Chapter

// #/components/schemas/github_com_rixlhq_api_internal_videos_handler_upload.CompleteRequest
type GithubComRixlhqAPIInternalVideosHandlerUploadCompleteRequest struct {
	VideoID *string `form:"video_id,omitempty" json:"video_id,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GithubComRixlhqAPIInternalVideosHandlerUploadCompleteRequest) ApplyDefaults() {
}

// #/components/schemas/github_com_rixlhq_api_internal_videos_handler_upload.InitResponse
type GithubComRixlhqAPIInternalVideosHandlerUploadInitResponse struct {
	PosterID           *string `form:"poster_id,omitempty" json:"poster_id,omitempty"`
	PosterPresignedURL *string `form:"poster_presigned_url,omitempty" json:"poster_presigned_url,omitempty"`
	UploadExpires      *int    `form:"upload_expires,omitempty" json:"upload_expires,omitempty"`
	VideoID            *string `form:"video_id,omitempty" json:"video_id,omitempty"`
	VideoPresignedURL  *string `form:"video_presigned_url,omitempty" json:"video_presigned_url,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GithubComRixlhqAPIInternalVideosHandlerUploadInitResponse) ApplyDefaults() {
}

// #/components/schemas/github_com_rixlhq_api_internal_videos_types.ChapterInput
type GithubComRixlhqAPIInternalVideosTypesChapterInput struct {
	StartTimeSec *float32 `form:"start_time_sec,omitempty" json:"start_time_sec,omitempty"`
	Title        *string  `form:"title,omitempty" json:"title,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GithubComRixlhqAPIInternalVideosTypesChapterInput) ApplyDefaults() {
}

// #/components/schemas/internal_images_handler.completeRequest
type InternalImagesHandlerCompleteRequest struct {
	AttachedToVideo *bool   `form:"attached_to_video,omitempty" json:"attached_to_video,omitempty"`
	ImageID         *string `form:"image_id,omitempty" json:"image_id,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *InternalImagesHandlerCompleteRequest) ApplyDefaults() {
}

// #/components/schemas/internal_images_handler.initResponse
type InternalImagesHandlerInitResponse struct {
	ImageID       *string `form:"image_id,omitempty" json:"image_id,omitempty"`
	PresignedURL  *string `form:"presigned_url,omitempty" json:"presigned_url,omitempty"`
	UploadExpires *int    `form:"upload_expires,omitempty" json:"upload_expires,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *InternalImagesHandlerInitResponse) ApplyDefaults() {
}

// #/components/schemas/internal_images_handler.uploadInitRequest
type InternalImagesHandlerUploadInitRequest struct {
	Format *string `form:"format,omitempty" json:"format,omitempty"`
	Name   *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *InternalImagesHandlerUploadInitRequest) ApplyDefaults() {
}

// #/components/schemas/internal_videos_handler_subtitles.languageResponse
type InternalVideosHandlerSubtitlesLanguageResponse struct {
	Code *string `form:"code,omitempty" json:"code,omitempty"`
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *InternalVideosHandlerSubtitlesLanguageResponse) ApplyDefaults() {
}

// #/components/schemas/pagination.PaginatedResponse-Image
type PaginationPaginatedResponseImage struct {
	// Data contains the slice of items for the current request.
	Data       []Image               `form:"data,omitempty" json:"data,omitempty"`
	Pagination *PaginationPagination `form:"pagination,omitempty" json:"pagination,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PaginationPaginatedResponseImage) ApplyDefaults() {
	if s.Pagination != nil {
		s.Pagination.ApplyDefaults()
	}
}

// #/components/schemas/pagination.PaginatedResponse-Image/properties/data
// Data contains the slice of items for the current request.
type PaginationPaginatedResponseImageData = []Image

// #/components/schemas/pagination.PaginatedResponse-Post
type PaginationPaginatedResponsePost struct {
	// Data contains the slice of items for the current request.
	Data       []Post                `form:"data,omitempty" json:"data,omitempty"`
	Pagination *PaginationPagination `form:"pagination,omitempty" json:"pagination,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PaginationPaginatedResponsePost) ApplyDefaults() {
	if s.Pagination != nil {
		s.Pagination.ApplyDefaults()
	}
}

// #/components/schemas/pagination.PaginatedResponse-Post/properties/data
// Data contains the slice of items for the current request.
type PaginationPaginatedResponsePostData = []Post

// #/components/schemas/pagination.PaginatedResponse-Video
type PaginationPaginatedResponseVideo struct {
	// Data contains the slice of items for the current request.
	Data       []Video               `form:"data,omitempty" json:"data,omitempty"`
	Pagination *PaginationPagination `form:"pagination,omitempty" json:"pagination,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PaginationPaginatedResponseVideo) ApplyDefaults() {
	if s.Pagination != nil {
		s.Pagination.ApplyDefaults()
	}
}

// #/components/schemas/pagination.PaginatedResponse-Video/properties/data
// Data contains the slice of items for the current request.
type PaginationPaginatedResponseVideoData = []Video

// #/components/schemas/pagination.Pagination
type PaginationPagination struct {
	// Maximum number of items to return in a single request.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
	// Starting point of the result set.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	// The total number of available items in the full list.
	Total *int `form:"total,omitempty" json:"total,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PaginationPagination) ApplyDefaults() {
	if s.Limit == nil {
		v := 25
		s.Limit = &v
	}
	if s.Offset == nil {
		v := 0
		s.Offset = &v
	}
}

// #/paths//videos/{videoId}/audio-tracks/post/responses/200/content/application/json/schema
type ReplaceAudioTracksJSONResponse = []AudioTrack

// #/paths//videos/{videoId}/subtitles/post/responses/200/content/application/json/schema
type ReplaceSubtitlesJSONResponse = []Subtitle

// #/paths//videos/languages/get/responses/200/content/application/json/schema
type ListLanguagesJSONResponse = []InternalVideosHandlerSubtitlesLanguageResponse

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/+xde3PbOJL/358C5bs9Z1x6WZYSR7Wzd7YTz2gn2XFsJ5PbqysNRLYkjEmAAUDbmux9",
	"9ysAfIsSSUmJX0zVlDV8AN2NRv+6G03AYq7HKFApBjsICWsGLtY/ETr2bcKuOLauzf8j5HHmAZcERHgF",
	"IYsDlmCPsIyvIQR32PUcGKDdbqfbbx50m92Dq4PuoNMZdDr/3E08KeceDJCQnNBpdHnCuLukQdc7LHqb",
	"2LlvHtJXN6+ve27XK2rAwWNwctu49DAlYlbcAJ36eAoji9mQ2xCI5tvLomYodvPfFoaMEVZD1CohEkH+",
	"zG+p2+kd9V+9XHifUAlT4NF1n+cLZCalJwbttmXTFid3TouwtqZqJJXmiLbH2R9gyRGx2zfEBqZ+aOab",
	"8XiU4SB8OZeKuyPa9fo3r69frW7GXGJjRVFGx9+AAxJWaboLQuBpvhh1O0izjGzdkl04JBJLX+S2xq4r",
	"snE6w54Evop62+dYEkZHy5V7t9MddPuFkxOoPZLEhZEAK7edg15/oQ3qu+OEOgmJuVzdSqeoDUmkkz8a",
	"Qyo5s31L8VtRkmfEgY3NXeeg2Tm40rZuU3OHb8hkTXt35t28u52/ef/FX9vOME6mhGKn9YcH06JW4pme",
	"29bJl9788MPJ4dHl2sbqoKSxWpxa/85hMkB7/9aO8a4dgF1bDfmlfmMvr1MO2J7HdtCztz/+RcaVuHgK",
	"wthXi7ntWJTtsoOcq+iXKTkB9d3wdxP5nsOwHTcQXokMW1MNuAVCJJ/xOHiYJ68kxddEwDnjO0upvGsq",
	"IpoWc93QJTH/YmrfqhYGpiE0w54HFOwGmhAHEBHIYpz7nsx58TyidoCwECD14z7nQKUzTzCDfpWzhDLF",
	"LVwoVgZRV5ozJBmyGBW+CzlvfAxENgiEhyZE4XYCHLLPavKCh1P0GVYXRHWDuZq9Ih64nBaX3ksMZp6g",
	"cm9mBzgjn5zrb6NBH7oJAM0zr1hKbM3AHkk20oifOy8m2BGwoO9jxhzAscGfkDQ8FNmAePbPgExncokJ",
	"OuoU2p8lFvD8sj98/ws7e+cWGQQ5893xDItZPg0frMufP1zQWe/14aeePZz14PPsYNa7/vvHYVHLt8SW",
	"S1p93S3ibMGInDMhvzta6kYZX4YzpxdHJXHGBmFx4ikvIbel93OEb0EwF5DHhCxEcQB7GVFnb8qC38a6",
	"Q9yMk7pK7/WEjBXfczAd6VZLvj8lcuaPRxZzRwqdZl9G2CMjezwSXxyrde5gejX3IBdXJxziOVylT6V0",
	"S1vVRuPbovWCXaouIDWtOMWOsXGi9Un9uQDhMSoivnJn21VCUGnA1uMe/V9SDsuBdhE9wj6GqdbCq5+i",
	"Vi/9ccr//m6pgSXzo+++vj7yujevvqwf3L+lU2c7wT1tflw/uAdDxkj4Y9ESXG7gLnd7Ww3sRTDoS6J6",
	"xXUzHogytH+bqD5Uzs1i+rCV+wjoP2rDFYT14gK++FCAtMGjye6JBDd1YQumSqODaAWUDanny70F3jDn",
	"eJ646lPyxYehJiflvBXybSziN2Y86G4DPr6VIn9KQk0e92MiOZYp/c2f5g9ETMpkWoNCxyzIVQ2KUkDr",
	"u/gTjl3IF12GmJnNB4WxxmLEUCYyyE+j3JcPpnxc4Gt6jgtxRan4Qeu3CUWHlMgSdk6N+GgpdLrzpp6I",
	"LdfrlfKTRytSb39403Lw9cXHDpHz7YyXFskH02LumIkZ41IEdzh88QkHO3bgIgEtk3k5dcn3MRP6otM/",
	"0W/LF5K58S08H2ExmjN/NF3LCw2oOEv2F148T/QbXjtN9x89iufH4r+Z/xMrwXpS8vnsj7EgVvR/qYFI",
	"iqMKp8lOT1LNJ+9cprtK3gqlUYDeOl8mWjoVk4XVZByMLiWmNuZ2kGHjwbOIg/Q5BRuN50jOAB2fD1eh",
	"csY1TnXx89XVeeAt6QfztLzXKU6z2CAxccTSfn7Vf7ETPojwmPlSU5/MQ6b6vZqBYkhNbBsN3yAiEGUS",
	"3WCHFDqAutGl1GjRhw5ncGtM6BTdzrBEt0AluuWMTvMXNDQBerpDUSai5IxfGYPWPkftczxRn6NcmDPD",
	"1HaAj0wqvnXKFPESSngoKyOBT8PXnz5/uPvt84dvMYezVBufqnhGm1EYbZx6DNrxOAgypWCPNljYinv9",
	"z8/NY/fP5rEzZZzImfvj8W+XvebP749Pm5c/H3f7L//DPHDKwQYqCXZ+PP5lePz28/H783dv/9I963a6",
	"/c7R4cFfume+aAIWsql+i8O/dM/wreiNArMatPMGS/gxfOfqoHPY6XT+Gdx7e+cRDuLHw5edTnDpUrP6",
	"M2AbuPhxxqJ21A0sfQ4/jrvdI3sM1pF10OkcWUcd6+BlFw66Bx3o9TuHtgWA7QPo2T273y9cLNRjOwJD",
	"SX7i52Wv8/p1v1sCQ7eirWEz5Qc+wJy8gY87rQd+c4uwmK5ZZQiWl2WUq8AoQ3dEoZn8oc1SalDWxG5z",
	"ldCEgRuavtJMkpIWeStUqaZrS7zmhHzVPxj37Nevjl4dHvQm9ksbf2/jXFqp/EoJlI0SHqsyL5qqVmEj",
	"y9nKODHRakMrXHEplQ/ORJ6l2ChDpoenhOoQoXVufoIdEtQsLGywscRLQ8M3WGJkMSoxoULHp8IhFiA2",
	"MfGSGjR9OSgHCePA1vqBVcaVXiOsiuVR1n1flCBhdG+ZUOJHtPAiGWR4rzZORQULD22YFL3Pb5QKlz0e",
	"2jBpgp/JOCVIzBsah7hEpsdmgn1HDlC3v4y49/iOuL4buJfxQEkWpB0RoQgjQejUgbzhSix5J1HVNe0u",
	"XCY0uFwYHrHJREA+O51l3FwqJ5rQKfIYoVJxYwQtfEciAfmE93MJLI7fJJPYWToVrmZgnkiIFt9g4uCx",
	"A4GQCdX0TXzHQQ5ZLte1CMzokwDL50TOL5UOh1pz7JFfYH7sx7mcFA/DwD1Ax+dDdA1zrboC+A2xoClZ",
	"M/iJLOa6PiWWUdagJUIHaKYdwp0E8qPPzePzYfMXmKfIxJoQfekEMI/zUmmZzj1Au+aBXTRhjsNuTVoc",
	"I+FhCxCmNvr7b1dIsmsookSxzTj5Eydq1VPUwJ1h/w2ztLxStOzu7pgKDvWL0Ik2mtr0WYHSgouJM0DC",
	"9zzG5X+F/v1OTMHF8PM7dGnu74QVIVFcEAUEInoiRcG/mvqd/f0Tnzg2wshjt8AnvmNSAgjuPOAEqAVo",
	"wpmLGG3a4CoJCckBu2qeSIbsOcUusZBgFsGOLqUT6JbIWTztj8+Hrf39Hd2dptn4iSLoKK7fbSBCpyC0",
	"rVMdTR021osADrkBPkeCoTnzkc3onkQzfKOmiBml31SHY584ktBQZMZSckyFxWzdupCM46kZZiG5b6nI",
	"wkYu2AQbyhvoV59rfXXxNQhEJAIsdK1wQAWakemsGSwcBq+qcVNwhCUSFnZA0aSAK3J4A41xHHRBpjMp",
	"0AUo5Q8qU/KHTQJ3RZNNwmmyE0btRoZmFecGuDD61G11dneYBxR7ZIAOWwetzo6H5UyrXlsz1/6q/gzt",
	"/zNETWPzmFKMC5CcwI0pnRTGgKsXG2ZYE7gSvK2gRF8Y2gNtiEKQwRy7kFxHaKZ7OgO9VLOzWHTZA/ti",
	"2D38/C6Oq+kAKX7SkQAyHEUXo1VVJLkfY7RB3oK4obkNaEN/HfO/of39NwHY7O8nOv292/99kdkEuiom",
	"v/jA5xkuNTSv4CYfqTcF0WZFdNS8XzGlWEpLAHVDQ5CmX4Ez6vYb6iX0uwHq35VclXxyJIh+7+SIrVMo",
	"NdNyGbGthZDhAmvChdrtdjq7yR4Cy5D2R7HnOQHatf8Qab8xn9B1fMpM7LTUv/z1l5j83n2Rv8Ya+FKG",
	"wiXXibEuiHGjHQl7FHPcfxocB46WBhWeWiMXvutiPh+gd0TIrEkP3RY8TX6GorBiETTaX9XL5dED686M",
	"76CHYjxHRIrY3qdgYwpPAzXUVMsl7rwvZDnijJi3QtyDMlHPywqdYBtdZIo+dnud3uPn7B9MojPmUztr",
	"YX4CGcz6SnYl+CpItL8Gv9b2UMNQDiwyIVb4uVF5v/VkfmpeeRKmKOAll77Tl7ykNYrGpPaxax+79rFr",
	"HzvPx26EZkL/rh3urMM9nocCWo2MZnm4rIPtOKbawKyLJIAv+MZrAfgQprEZF0xbmo2TOLUNr214FfGc",
	"EXBsxYVSQDUzXsRfmzY0RQ39YWQj8Q3wD4tsxS8V8icYlxu5KZeKUsZt4OgFFlZD382hSV0ulja3kxue",
	"PLowrria4vnB4HK463UOHj+bHykOFrsS39Lu9jqHj5+1M8bHxLaBPicPJVjLjQE9sZCL/ud/cx2ZlKcR",
	"OBi5zow2ASL6ekqbuwHqxu5N+6v+G0X5dupb7xQX5hbC1HSv0MLF/FqBK5EIi8wH3ikfxtwq68VoqnND",
	"5fcH/l25UDlg6xtm7tLZoxwGAnkg4VsWCDHxHWf+RG1uoINBhp9kx6+2vA+ctWOtocgGStK8PYEUqZmM",
	"lEk0SSRKnwq2nGHigB3URCj7nNzApiq4vFlsogye9EvGyAnkMItPS2Ll1oaLUo8DP+5J+Z5pVFBj0hOI",
	"Bmo8elaxzk8gK2PRQSK2MV/0tMNP4syrXuLbhfQSXfCYzhAGe4cG5ZC6SNEkufRdY0w4WIzbyNe7ncYb",
	"OSBdXqumJVAZDFUeoJkuwl4TO5GAkCfMnic/xllQhNVqkK8Eq1Sg5OeEe5km07bIyCx4hTCas9FCanyz",
	"tyu2lgvJNdbeP9YGA4XGzJ4/YbxVNijgOCiqr6PCx+NdEOc5BIWh/Q4BjfEQxzaJE/eMcR6g95hfIyyi",
	"bvYqIHVvEakJDT96WorSQ0okwQ75Uxc1hh9mo48X76LNwVVMGYaaepfxCKFTc7QsQqseHyg6L3yyXAaf",
	"SShBvC2MLmjx4eN0mX0GahivYfxJwfgTQzoSA4Mxi5timzKrVfDsUOGZ2XyhQtGQeaEuGqqLhp500VAj",
	"2hmwLh96JOVDC7sx1OVD9YJBXT70BMqHUj7HqvIhbQLyy4dMG+2v+m+VDxHNPgPfeglYU567BPzpkJT8",
	"Gihg7ektAT9Ty36T1YnaotdLwPfCl7FO9RJwuSVgnD6GqwRCHeQhlDlQuWkOVC6sdr0AlwUhOrZtEmyB",
	"j+MDioX5mj4EtFSOuURu2XQdH5wsamTbghpnD6IuBrk1S+S0XiSUoYpydlqHq9c4LsBz9A5YmU5MkkEm",
	"z1ZgFERl3eOm/SehfOUWZFzfkcTDXLYnjLvN7MaHCAE1+1Jl1W1CHBCLOgh3nsNsyJAckS7neudkxt0S",
	"Cz952/8VdJ9N8God0c+iFy3XO2ygFvN80UCtiYOtBmrd4psGamFL3XF7uJHTIkItjBOZkPhfzi6OEX1m",
	"G1w0JhTzee4juTvHZm9nt3g0//QZg8XsnzLXxU0BSnsl2MFrOW9ljyhsXHqYpo8qLEV16ujCdegzr+tN",
	"dlfSqc8CbOhz/qvRmD3QKPxnDjYSC1fTHOXczpHowiaXW9BLo4PoX1mZ7SwK30hv8dEssQ9j9XHpHCqH",
	"Zns75ebNdjDuxHeuke8J4EGuYH2oK3TE2l/13zIfIIUuGV3ikW3XIXuskNjMm4Oao1wij19JXo7IYJxq",
	"p7FOHdSpgwez4dOTSxpcmqTB2w2SBmGMFkNDFcwqTh60Qx+k/VX90k5TJfhKYlY6/R15N5vC18n8XdDU",
	"EwGykB10ymxAL05Oz1HvVc7CbfrU8CV0RsNWo9k2phcazyPNrZYJ6ZpMiJ+fCDm2dcUqD/MhFadO5Q8y",
	"bFxPofuaQltK5KyXY6mQYqkUye6skTIpSD2MwSmk9p16Cr2A1rQV5jp+KJEP2WaOYYNkQdVcgeY20d8S",
	"vh9+GXJ+vL8do/1xSThfzVzn+0bpE2rLLaqE72wjaA/O5auXULahhB81CoYirVj9XpeG11941Yvs97Lv",
	"h5U2gms69cYMZ9oqBQ6HKz355JJmbPq1A2+6fIElc4mFzj9exSb+hw19+ccPDPfzvVkWA4q/LQufzV3J",
	"K/cx2ZImHr7bthFiPtHvxVTYbiZ2WPevLXF0alrtNNROQ+003J/TYPBxU6fBWL4NnIbcUvJ2MoJcEU2G",
	"eciFkvJbImf6k7V0bfsGO1I+johxxY6UhoFnuyNlXfpdg0wNMvcUmSartzcJSysASz8XV6Kj8KskKqOX",
	"tpGpvAwbq1OVW9DaUJrfodZbZAaujBIeVanzjtVsu0XeT0Dj6hLvAQqHMaqmFfozdtS6kbKu2a5rtrdW",
	"s71S0XKrrZcI5ikXZodCuu+y7LVQabVr1P4a/qxSkh1Rsk0n6YlU3UQzKo/Cy54/LkdhPCy1I1fH73X9",
	"dV1//dDrr0XajpcBp9cF4LRR4XUCpLZadB1ar2dcL/qM662/UxIi0t31Sq2PKlZaV5wrlTbVtXE9Z+5h",
	"zjzsAutU3Fmc36irqHcqizEslX68BdJ5cfc3KI9ew3E5WlIaLWe+O6aYBNq2zPwGC+lypv4L3gh3MDfb",
	"mcMdEXpP0pzIurL1vQr7ePZJ4erWLDOiK+zHVXYk9ZR08R3qvz9pmIvt/W1bt+UGRWZGvbxVqcrJw7ck",
	"q7fAM+quF2KCLWxzhPe06iX0kGoPMF2iWdfn1aUTdenE91LT6JCWoD5vomsptlGdl7VfZZyalwmXJoz7",
	"Cva2/wmk3nsesQkSvucxnlwkMiX/2VWLhY3rwxhKPKpFoWjIjcTCQ0RGEbutUAx5erDG8lFqT9+osjqO",
	"3J2MGJcMeTjC1U7LMyf/hN6o0dvEQUAITyTwRKFh+IxkSEjG44AfVc66PaiD8wqmf0YXDOmt0wqn6n1K",
	"SnhLZ+uVbfOx+3H10Ty1q1a7ave1AvgsT9j7Pifq5ftrvUU0r3qiXhrPqW2OuEkes2d8uGAfgcS4qvaB",
	"rwnmD+CMPS3Sj5UO1EvB6BaP1avS7sOH6LU8pGF98l4N7/XJe/XJe2Vw73DHnDQgBjtN5HNngGZSemLQ",
	"bmOPtBSnLYu57R3TVmZpY29//8Qnjo3sOcUusZBgFsEOgjsPOAFqgWjt7/91zP+m/jsDsAXCHMzZX6DC",
	"J8cBS7Vl6GITdM6EFPpkMYOak/DUXb1+A1zhoRN+NYk58wU4oqHjYgKigRgPiZDEBYdQEOY8nLfYmunW",
	"tcpgQgWaM58jF2yC0QvTIuMmIf+Dxm8iBcJCNyfBRi5IbGOJW0q+Zl1Gs5QjlTAZRS1QtHHALvKAT8CS",
	"zhxhOr+dAYeEbC6Gn9/t7Ql9eJzjkClQA1PBIfr6QD3iaX4QptiZ/wkB/ZE3gSTHVJidnYnUgmOeJC52",
	"0BcfO0QaC6GeVKQw7mJqQQv9BsgAiF5CM77THZFzJJjqAVmYIhsccgP6yCPDBfIcPB+HeyDF443gBvhc",
	"yz4hpkD1FuX0Jmh3goVsJCRkFnGU0M2pshlJKd+IuVjrQvAVpmFBBIssmvEA9htBa2rclaLrS0oKemXm",
	"ZyxmaAo0cKta6NgJVmqMSip11TPERjcEIyXxqcPG2EGnb/4RnZdsA3aQL4AnRJHgPzj08v8DAAD//xyG",
	"sEjq3gAA",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
