// Code generated by oapi-codegen; DO NOT EDIT.

package models

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"
	"sync"
)

// #/components/schemas/AudioTrack
type AudioTrack struct {
	CreatedAt    *string `form:"created_at,omitempty" json:"created_at,omitempty"`
	Format       *string `form:"format,omitempty" json:"format,omitempty"`
	ID           *string `form:"id,omitempty" json:"id,omitempty"`
	Label        *string `form:"label,omitempty" json:"label,omitempty"`
	LanguageCode *string `form:"language_code,omitempty" json:"language_code,omitempty"`
	Name         *string `form:"name,omitempty" json:"name,omitempty"`
	Size         *int    `form:"size,omitempty" json:"size,omitempty"`
	URL          *string `form:"url,omitempty" json:"url,omitempty"`
	VideoID      *string `form:"video_id,omitempty" json:"video_id,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AudioTrack) ApplyDefaults() {
}

// #/components/schemas/AudioTrackDelete
type AudioTrackDelete struct {
	Message *string `form:"message,omitempty" json:"message,omitempty"`
	Status  *string `form:"status,omitempty" json:"status,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AudioTrackDelete) ApplyDefaults() {
}

// #/components/schemas/Chapter
type Chapter struct {
	DurationLabel *string  `form:"duration_label,omitempty" json:"duration_label,omitempty"`
	EndTimeSec    *float32 `form:"end_time_sec,omitempty" json:"end_time_sec,omitempty"`
	StartTimeSec  *float32 `form:"start_time_sec,omitempty" json:"start_time_sec,omitempty"`
	Title         *string  `form:"title,omitempty" json:"title,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Chapter) ApplyDefaults() {
}

// #/components/schemas/File
type File struct {
	CreatedAt *string     `form:"created_at,omitempty" json:"created_at,omitempty"`
	Format    *string     `form:"format,omitempty" json:"format,omitempty"`
	ID        *string     `form:"id,omitempty" json:"id,omitempty"`
	Name      *string     `form:"name,omitempty" json:"name,omitempty"`
	ProjectID *string     `form:"project_id,omitempty" json:"project_id,omitempty"`
	Size      *int        `form:"size,omitempty" json:"size,omitempty"`
	Status    *FileStatus `form:"status,omitempty" json:"status,omitempty"`
	UpdatedAt *string     `form:"updated_at,omitempty" json:"updated_at,omitempty"`
	URL       *string     `form:"url,omitempty" json:"url,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *File) ApplyDefaults() {
}

// #/components/schemas/FileStatus
type FileStatus string

const (
	FileStatusUploading  FileStatus = "uploading"
	FileStatusUploaded   FileStatus = "uploaded"
	FileStatusProcessing FileStatus = "processing"
	FileStatusPreparing  FileStatus = "preparing"
	FileStatusReady      FileStatus = "ready"
	FileStatusError      FileStatus = "error"
)

// #/components/schemas/Image
type Image struct {
	AttachedToVideo *bool   `form:"attached_to_video,omitempty" json:"attached_to_video,omitempty"`
	File            *File   `form:"file,omitempty" json:"file,omitempty"`
	Height          *int    `form:"height,omitempty" json:"height,omitempty"`
	ID              *string `form:"id,omitempty" json:"id,omitempty"`
	Thumbhash       *string `form:"thumbhash,omitempty" json:"thumbhash,omitempty"`
	Width           *int    `form:"width,omitempty" json:"width,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Image) ApplyDefaults() {
	if s.File != nil {
		s.File.ApplyDefaults()
	}
}

// #/components/schemas/Post
type Post struct {
	CreatedAt   *string                                        `form:"created_at,omitempty" json:"created_at,omitempty"`
	CreatorID   *string                                        `form:"creator_id,omitempty" json:"creator_id,omitempty"`
	Description *string                                        `form:"description,omitempty" json:"description,omitempty"`
	FeedID      *string                                        `form:"feed_id,omitempty" json:"feed_id,omitempty"`
	ID          *string                                        `form:"id,omitempty" json:"id,omitempty"`
	Image       *Image                                         `form:"image,omitempty" json:"image,omitempty"`
	PlanType    *GithubComRixlhqAPIDBSqlcPlanType              `form:"plan_type,omitempty" json:"plan_type,omitempty"`
	Type        *PostType                                      `form:"type,omitempty" json:"type,omitempty"`
	UpdatedAt   *string                                        `form:"updated_at,omitempty" json:"updated_at,omitempty"`
	Video       *GithubComRixlhqAPIInternalVideosVideoResponse `form:"video,omitempty" json:"video,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Post) ApplyDefaults() {
	if s.Image != nil {
		s.Image.ApplyDefaults()
	}
	if s.Video != nil {
		s.Video.ApplyDefaults()
	}
}

// #/components/schemas/PostType
type PostType string

const (
	PostTypeImage PostType = "image"
	PostTypeVideo PostType = "video"
)

// #/components/schemas/Subtitle
type Subtitle struct {
	CreatedAt    *string `form:"created_at,omitempty" json:"created_at,omitempty"`
	ID           *string `form:"id,omitempty" json:"id,omitempty"`
	Label        *string `form:"label,omitempty" json:"label,omitempty"`
	LanguageCode *string `form:"language_code,omitempty" json:"language_code,omitempty"`
	Name         *string `form:"name,omitempty" json:"name,omitempty"`
	Size         *int    `form:"size,omitempty" json:"size,omitempty"`
	URL          *string `form:"url,omitempty" json:"url,omitempty"`
	VideoID      *string `form:"video_id,omitempty" json:"video_id,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Subtitle) ApplyDefaults() {
}

// #/components/schemas/SubtitleDelete
type SubtitleDelete struct {
	Message *string `form:"message,omitempty" json:"message,omitempty"`
	Status  *string `form:"status,omitempty" json:"status,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *SubtitleDelete) ApplyDefaults() {
}

// #/components/schemas/UpdateChaptersRequest
type UpdateChaptersRequest struct {
	Chapters []GithubComRixlhqAPIInternalVideosTypesChapterInput `form:"chapters,omitempty" json:"chapters,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *UpdateChaptersRequest) ApplyDefaults() {
}

// #/components/schemas/UpdateChaptersRequest/properties/chapters
type UpdateChaptersRequestChapters = []GithubComRixlhqAPIInternalVideosTypesChapterInput

// #/components/schemas/UpdateChaptersResponse
type UpdateChaptersResponse struct {
	Chapters []Chapter `form:"chapters,omitempty" json:"chapters,omitempty"`
	VideoID  *string   `form:"video_id,omitempty" json:"video_id,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *UpdateChaptersResponse) ApplyDefaults() {
}

// #/components/schemas/UpdateChaptersResponse/properties/chapters
type UpdateChaptersResponseChapters = []Chapter

// #/components/schemas/Video
type Video struct {
	Bitrate   *int                              `form:"bitrate,omitempty" json:"bitrate,omitempty"`
	Chapters  []Chapter                         `form:"chapters,omitempty" json:"chapters,omitempty"`
	Codec     *string                           `form:"codec,omitempty" json:"codec,omitempty"`
	Duration  *float32                          `form:"duration,omitempty" json:"duration,omitempty"`
	File      *File                             `form:"file,omitempty" json:"file,omitempty"`
	Framerate *string                           `form:"framerate,omitempty" json:"framerate,omitempty"`
	Hdr       *bool                             `form:"hdr,omitempty" json:"hdr,omitempty"`
	Height    *int                              `form:"height,omitempty" json:"height,omitempty"`
	ID        *string                           `form:"id,omitempty" json:"id,omitempty"`
	PlanType  *GithubComRixlhqAPIDBSqlcPlanType `form:"plan_type,omitempty" json:"plan_type,omitempty"`
	Poster    *Image                            `form:"poster,omitempty" json:"poster,omitempty"`
	Width     *int                              `form:"width,omitempty" json:"width,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Video) ApplyDefaults() {
	if s.File != nil {
		s.File.ApplyDefaults()
	}
	if s.Poster != nil {
		s.Poster.ApplyDefaults()
	}
}

// #/components/schemas/Video/properties/chapters
type VideoChapters = []Chapter

// #/components/schemas/VideoUploadInitRequest
type VideoUploadInitRequest struct {
	FileName     string                                `form:"file_name" json:"file_name"`
	ImageFormat  *string                               `form:"image_format,omitempty" json:"image_format,omitempty"`
	VideoQuality *GithubComRixlhqAPIDBSqlcVideoQuality `form:"video_quality,omitempty" json:"video_quality,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *VideoUploadInitRequest) ApplyDefaults() {
}

// #/components/schemas/github_com_rixlhq_api_db_sqlc.PlanType
type GithubComRixlhqAPIDBSqlcPlanType string

const (
	PlanTypeFree       GithubComRixlhqAPIDBSqlcPlanType = "free"
	PlanTypePro        GithubComRixlhqAPIDBSqlcPlanType = "pro"
	PlanTypeCustom     GithubComRixlhqAPIDBSqlcPlanType = "custom"
	PlanTypePayAsYouGo GithubComRixlhqAPIDBSqlcPlanType = "pay_as_you_go"
)

// #/components/schemas/github_com_rixlhq_api_db_sqlc.VideoQuality
type GithubComRixlhqAPIDBSqlcVideoQuality string

const (
	VideoQualityBasic  GithubComRixlhqAPIDBSqlcVideoQuality = "basic"
	VideoQualityShorts GithubComRixlhqAPIDBSqlcVideoQuality = "shorts"
	VideoQualityPro    GithubComRixlhqAPIDBSqlcVideoQuality = "pro"
)

// #/components/schemas/github_com_rixlhq_api_internal_errors.ErrorResponse
// Standard error response returned by the API
type GithubComRixlhqAPIInternalErrorsErrorResponse struct {
	// HTTP status code
	Code *int `form:"code,omitempty" json:"code,omitempty"`
	// Optional details about the error
	Details *string `form:"details,omitempty" json:"details,omitempty"`
	// Error message describing what went wrong
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GithubComRixlhqAPIInternalErrorsErrorResponse) ApplyDefaults() {
}

// #/components/schemas/github_com_rixlhq_api_internal_videos.VideoResponse
type GithubComRixlhqAPIInternalVideosVideoResponse struct {
	Bitrate   *int                              `form:"bitrate,omitempty" json:"bitrate,omitempty"`
	Chapters  []Chapter                         `form:"chapters,omitempty" json:"chapters,omitempty"`
	Codec     *string                           `form:"codec,omitempty" json:"codec,omitempty"`
	Duration  *float32                          `form:"duration,omitempty" json:"duration,omitempty"`
	File      *File                             `form:"file,omitempty" json:"file,omitempty"`
	Framerate *string                           `form:"framerate,omitempty" json:"framerate,omitempty"`
	Hdr       *bool                             `form:"hdr,omitempty" json:"hdr,omitempty"`
	Height    *int                              `form:"height,omitempty" json:"height,omitempty"`
	ID        *string                           `form:"id,omitempty" json:"id,omitempty"`
	PlanType  *GithubComRixlhqAPIDBSqlcPlanType `form:"plan_type,omitempty" json:"plan_type,omitempty"`
	Poster    *Image                            `form:"poster,omitempty" json:"poster,omitempty"`
	Width     *int                              `form:"width,omitempty" json:"width,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GithubComRixlhqAPIInternalVideosVideoResponse) ApplyDefaults() {
	if s.File != nil {
		s.File.ApplyDefaults()
	}
	if s.Poster != nil {
		s.Poster.ApplyDefaults()
	}
}

// #/components/schemas/github_com_rixlhq_api_internal_videos.VideoResponse/properties/chapters
type GithubComRixlhqAPIInternalVideosVideoResponseChapters = []Chapter

// #/components/schemas/github_com_rixlhq_api_internal_videos_handler_upload.CompleteRequest
type GithubComRixlhqAPIInternalVideosHandlerUploadCompleteRequest struct {
	VideoID *string `form:"video_id,omitempty" json:"video_id,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GithubComRixlhqAPIInternalVideosHandlerUploadCompleteRequest) ApplyDefaults() {
}

// #/components/schemas/github_com_rixlhq_api_internal_videos_handler_upload.InitResponse
type GithubComRixlhqAPIInternalVideosHandlerUploadInitResponse struct {
	PosterID           *string `form:"poster_id,omitempty" json:"poster_id,omitempty"`
	PosterPresignedURL *string `form:"poster_presigned_url,omitempty" json:"poster_presigned_url,omitempty"`
	UploadExpires      *int    `form:"upload_expires,omitempty" json:"upload_expires,omitempty"`
	VideoID            *string `form:"video_id,omitempty" json:"video_id,omitempty"`
	VideoPresignedURL  *string `form:"video_presigned_url,omitempty" json:"video_presigned_url,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GithubComRixlhqAPIInternalVideosHandlerUploadInitResponse) ApplyDefaults() {
}

// #/components/schemas/github_com_rixlhq_api_internal_videos_types.ChapterInput
type GithubComRixlhqAPIInternalVideosTypesChapterInput struct {
	StartTimeSec *float32 `form:"start_time_sec,omitempty" json:"start_time_sec,omitempty"`
	Title        *string  `form:"title,omitempty" json:"title,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GithubComRixlhqAPIInternalVideosTypesChapterInput) ApplyDefaults() {
}

// #/components/schemas/internal_images_handler.completeRequest
type InternalImagesHandlerCompleteRequest struct {
	AttachedToVideo *bool   `form:"attached_to_video,omitempty" json:"attached_to_video,omitempty"`
	ImageID         *string `form:"image_id,omitempty" json:"image_id,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *InternalImagesHandlerCompleteRequest) ApplyDefaults() {
}

// #/components/schemas/internal_images_handler.initResponse
type InternalImagesHandlerInitResponse struct {
	ImageID       *string `form:"image_id,omitempty" json:"image_id,omitempty"`
	PresignedURL  *string `form:"presigned_url,omitempty" json:"presigned_url,omitempty"`
	UploadExpires *int    `form:"upload_expires,omitempty" json:"upload_expires,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *InternalImagesHandlerInitResponse) ApplyDefaults() {
}

// #/components/schemas/internal_images_handler.uploadInitRequest
type InternalImagesHandlerUploadInitRequest struct {
	Format *string `form:"format,omitempty" json:"format,omitempty"`
	Name   *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *InternalImagesHandlerUploadInitRequest) ApplyDefaults() {
}

// #/components/schemas/internal_videos_handler_subtitles.languageResponse
type InternalVideosHandlerSubtitlesLanguageResponse struct {
	Code *string `form:"code,omitempty" json:"code,omitempty"`
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *InternalVideosHandlerSubtitlesLanguageResponse) ApplyDefaults() {
}

// #/components/schemas/pagination.PaginatedResponse-Image
type PaginationPaginatedResponseImage struct {
	// Data contains the slice of items for the current request.
	Data       []Image               `form:"data,omitempty" json:"data,omitempty"`
	Pagination *PaginationPagination `form:"pagination,omitempty" json:"pagination,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PaginationPaginatedResponseImage) ApplyDefaults() {
	if s.Pagination != nil {
		s.Pagination.ApplyDefaults()
	}
}

// #/components/schemas/pagination.PaginatedResponse-Image/properties/data
// Data contains the slice of items for the current request.
type PaginationPaginatedResponseImageData = []Image

// #/components/schemas/pagination.PaginatedResponse-Post
type PaginationPaginatedResponsePost struct {
	// Data contains the slice of items for the current request.
	Data       []Post                `form:"data,omitempty" json:"data,omitempty"`
	Pagination *PaginationPagination `form:"pagination,omitempty" json:"pagination,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PaginationPaginatedResponsePost) ApplyDefaults() {
	if s.Pagination != nil {
		s.Pagination.ApplyDefaults()
	}
}

// #/components/schemas/pagination.PaginatedResponse-Post/properties/data
// Data contains the slice of items for the current request.
type PaginationPaginatedResponsePostData = []Post

// #/components/schemas/pagination.PaginatedResponse-Video
type PaginationPaginatedResponseVideo struct {
	// Data contains the slice of items for the current request.
	Data       []Video               `form:"data,omitempty" json:"data,omitempty"`
	Pagination *PaginationPagination `form:"pagination,omitempty" json:"pagination,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PaginationPaginatedResponseVideo) ApplyDefaults() {
	if s.Pagination != nil {
		s.Pagination.ApplyDefaults()
	}
}

// #/components/schemas/pagination.PaginatedResponse-Video/properties/data
// Data contains the slice of items for the current request.
type PaginationPaginatedResponseVideoData = []Video

// #/components/schemas/pagination.Pagination
type PaginationPagination struct {
	// Maximum number of items to return in a single request.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
	// Starting point of the result set.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	// The total number of available items in the full list.
	Total *int `form:"total,omitempty" json:"total,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PaginationPagination) ApplyDefaults() {
	if s.Limit == nil {
		v := 25
		s.Limit = &v
	}
	if s.Offset == nil {
		v := 0
		s.Offset = &v
	}
}

// #/paths//videos/{videoId}/audio-tracks/post/responses/200/content/application/json/schema
type PostVideosVideoIDAudioTracks200Response = []AudioTrack

// #/paths//videos/{videoId}/subtitles/post/responses/200/content/application/json/schema
type PostVideosVideoIDSubtitles200Response = []Subtitle

// #/paths//videos/languages/get/responses/200/content/application/json/schema
type GetVideosLanguages200Response = []InternalVideosHandlerSubtitlesLanguageResponse

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/+xde1MbuZb/n0+hYvcuuRR+YExCXDd3l5Aw8Z3kDgGSyd6tLY/cfWxr6JY6khrwZPa7",
	"b0nqt2V32yYBTE/VFE4/1Oel8ztHOpIc5geMApWit4WQcCbgY/0ToePQJeySY+fK/BuhgLMAuCQg4isI",
	"ORywBHeAZXoNIbjFfuBBD2132p3Dxn6n0dm/3O/02u1eu/2v7cyTchpADwnJCR0nl0eM+3Ma9IODsreJ",
	"a33zgL64fnnV9TtBWQMeHoJnbeMiwJSISXkDdBziMQwc5oK1IRCNtxdlzVDs298WhowBVipqVhCJIH/Y",
	"W+q0u0eHL57PvE+ohDHw5HrI7QKZSBmIXqvluLTJya3XJKylqRpIZTmiFXD2OzhyQNzWNXGBqR+a+Uaq",
	"jyocxC9bqbg9op3g8Prl1YvFzZhLbKgoKtj4G/BAwiJL90EIPLaLUbeDNMvI1S25pSqRWIbC2hq7WpKN",
	"kwkOJPBF1Lshx5IwOphv3NvtTq9zWNo5gboDSXwYCHCs7ex3D2faoKE/zJiTkJjLxa20y9qQRHp2bfSp",
	"5MwNHcXvkpI8JR6s7e7a+432/qX2deu6O3xNRiv6u9Pg+v3N9M2Hr+HKfoZxMiYUe83fAxiXtZL2dGtb",
	"r792pwcfXx8cXazsrPYrOqvZrvXvHEY9tPNvrRTvWhHYtZTKL/QbO7aPcsDuNPWDgXv3+i9zrsTHYxDG",
	"vzrMb6WibFVVstXQL3JyAhr68e8GCgOPYTdtIL6SOLaGUrgDQmSfCTgEmGevZMXXQMA541tzqbxtKCIa",
	"DvP9OCQx/6XUvlUt9ExDaIKDACi4e2hEPEBEIIdxHgbS8uJZQm0PYSFA6sdDzoFKb5phBv0iJxljSls4",
	"V6z0kk9pzpBkyGFUhD5Y3vgUiawXCQ+NiMLtDDgUn9XkRQ/n6DOszojqGnPVe0WqOEuLc+9llGkTlPVm",
	"UcEF+Viuv02U3vczAGpzr1hK7EzAHUg20Ihv7Rcj7AmYsfchYx7g1OGPSB4eynxA2vsnQMYTOccFHbVL",
	"/c8cD3h2cdj/8DM7fe+XOQQ5Cf3hBIuJnYaPzsW7j+d00n158Lnr9idd+DLZn3Sv/vGpX9byDXHlnFZf",
	"dso4m3EiZ0zIH46WulHG5+HMyflRRZxxQTicBCpKsLb0YYrwDQjmAwqYkKUoDuDOI+r0TVXwW9t2iF8I",
	"UhfZve6QqeEHHqYD3WrF98dETsLhwGH+QKHT5OsAB2TgDgfiq+c0zzxML6cBWHF1xCHtw8t8Uxnd3Fa1",
	"0/i+aD3jl5YXkOpWnGLP+DjR/Kz+nIMIGBUJX9bedpkRVB6wtd6Tf2XlMB9oZ9Ej/kY/11p89XPS6kU4",
	"zMXfP2xoYE7/OPRfXh0FnesXX1dP7t/SsXc3yT1tfFo9uQdDxkCEQ9EUXK4RLne6d5rYi0jpc7J6xXUj",
	"VUQV2r9PVh8b53o5fdzKfST0n7TjitJ6cQ5fQyhB2ujR7OeJBD934Q5clUYH0Ywo69MglDszvGHO8TRz",
	"NaTkawh9TU4ueCvl23jE78x49Lk1+Phehvw5CzU27odEcixz9mvv5g9ETMplOr3SwCwaq+qVDQGtHuKP",
	"OPbBLroCMROX90pzjdmMoUpmYB9Gua8YTMW4wFeMHGfyikr5g7Zvk4r2KZEV/JzS+GAudPrThu6ITT/o",
	"VoqTBwuG3n4PxtXg62uIPSKnd6MvLZKPpkWrzsSEcSmiOxy+hoSDmwZwiYDmybyaudhjzIy96OGf5LcT",
	"Csn89BaeDrAYTFk4GK8UhUZUnGa/F188y3w3vnaS/37yKJ4ei/9m4U+sAutZydvZH2JBnORfOUVkxbEM",
	"p9mPvs41n71zkf9U9lYsjRL01uNloqmHYoqwms2D0YXE1MXcjUbYePQs4iBDTsFFwymSE0DHZ/1FqFwI",
	"jXOfeHd5eRZFS/pBm5V32+XDLC5ITDwx9zu/6L/Yix9EeMhCqanPjkPmvns5AcWQ6tgu6r9BRCDKJLrG",
	"HikNAHWjc6nRoo8DzujWkNAxuplgiW6ASnTDGR3bJzQ0Abq7Q9lIRMUevzAHrWOOOubY0JijWpozwdT1",
	"gA/MUHzzhCniJVSIUBZmAp/7Lz9/+Xj765eP36MPF6k2MVV5jzZaGKw99Bi1E3AQZEzBHawxsZV+9T+/",
	"NI79PxrH3phxIif+q+NfL7qNdx+OTxoX7447h8//wzxwwsEFKgn2Xh3/3D9+++X4w9n7t3/pnHbancP2",
	"0cH+XzqnoWgAFrKhfouDv3RO8Y3oDiK3GrXzBkt4Fb9zud8+aLfb/4ruvb0NCAfx6uB5ux1dutCsvgPs",
	"AhevJixpR93AMuTwatjpHLlDcI6c/Xb7yDlqO/vPO7Df2W9D97B94DoA2N2Hrtt1Dw9LJwu1bgdgKLEP",
	"/Dzvtl++POxUwNA7sda4meqKjzDHpvj0o7Xi1/cIs8M1ixzB/LKMahUYVehOKDSdP/ZZygyquti7nCU0",
	"aeCarq8yk6SiR74TqlTTtSdesUO+ONwfdt2XL45eHOx3R+5zF/9o51zZqMKlBlDWGvBYNPKiqWqWNjKf",
	"rUIQk8w2NOMZl0rjwYXMsxIbVcgM8JhQnSI0z8xPcGOCGqWFDS6WeG5q+AZLjBxGJSZU6PxUeMQBxEYm",
	"X1JK05ejcpA4D2yunlgVQukV0qpUHlXD91kJEkZ35gklfUQLL5FBgffl9FRWsPDQ1KTofXpaKp32eGhq",
	"0gQ/ET1lSLSpxiM+kXndjHDoyR7qHM4j7gO+JX7oR+FlqijJomFHRCjCSBA69sCmrsyUdxZVfdPuzGVC",
	"o8ul6REbjQTY2WnP4+ZCBdGEjlHACJWKGyNoEXoSCbATfmglsDx/k0xib25XuJyAeSIjWnyNiYeHHkRC",
	"JlTTNwo9D3lkvlxXIrBgTwKckBM5vVA2HFvNcUB+hulxmI7l5HjoR+EBOj7royuYatMVwK+JAw3JGtFP",
	"5DDfDylxjLFGLRHaQxMdEG5lkB99aRyf9Rs/wzRHJtaE6EuvAfN0XCov02kAaNs8sI1GzPPYjRkWx0gE",
	"2AGEqYv+8eslkuwKyihRbDNO/sCZWvUcNXBr2H/DHC2vHC3b21umgkP9InSknaZ2fU5ktOBj4vWQCIOA",
	"cflfcXy/lVJw3v/yHl2Y+1txRUiSFyQJgUieyFHwZ0O/s7v7OiSeizAK2A3wUeiZIQEEtwFwAtQBNOLM",
	"R4w2XPCVhITkgH3VTyRD7pRinzhIMIdgT5fSCXRD5CTt9sdn/ebu7pb+nKbZxIki+lBav7uHCB2D0L5O",
	"fWjssaGeBPDINfApEgxNWYhcRnckmuBr1UWMln5VHxyGxJOExiIznpJjKhzm6taFZByPjZqF5KGjMgsX",
	"+eASbCjfQ7+EXNurj69AICIRYKFrhSMq0ISMJ41o4jB6VelNwRGWSDjYA0WTAq4k4I0sxvPQORlPpEDn",
	"oIw/qkyxq00C90WDjeJushVn7UaGZhbnGrgw9tRptre3WAAUB6SHDpr7zfZWgOVEm15LM9f6pv703f8z",
	"RI1T95gzjHOQnMC1KZ0UxoGrF/eMWjO4EoMJ5tiH7HxBI9/iKegpma3Z4souuOf9zsGX92n+THtI0Z2P",
	"+JGhPLmYzJ4iycMUiw3CluQHjbuAMPS3If872t19E4HK7m7mo791Dn+bZTaDoorJryHwaYFLDcELuLEj",
	"8rpg2VgSBTXvl0wZkLIGQJ24w+fpVyCMOod76iX0mwHk35RclXwsEkS/tS1ia5dKzbRcRWwrIWE8kZoJ",
	"lbY77fZ29guRB8jHnTgIvAjVWr+LfHxoJ3SV2LGQI82NI3/5OSW/e1/krzDXPZeheGp1ZLwLYtxYR8Yf",
	"pRwfbgbHUUClwYPn5sJF6PuYT3voPRGy6Lrj8ASPs8tNFCbMgkPrm3q5Okpg/TETI2hVDKeISJH6+8cN",
	"D6pPWYk7OxSyGnFGnndC3IPyRU/L3bzGLjovVHFsd9vdx8/ZP5lEpyykbtGV/AQy6t5LOZBomY9ofYt+",
	"rRxyxrkZOGREnHj90IYGoieGOyt9J895RWeTiLyOletYuY6V61jZFivvxW5C/64D52LgPJzGAloMfGY6",
	"t2qg7HmmOsDMY2RwLVqTNYNrCNPUjQumPU1lrKt9de2rlxHPKQHPVVwoQ1M94Fm6CnRPU7SnFyzuZdbm",
	"/nWWrfSlUv4E43KtcORCUcq4Cxw9w8LZ03ctNKnL5dLmbnYjkkeXjZVXOTw9uJsPa932/uNn8xPF0SRU",
	"Zo3rdrd98PhZO2V8SFwX6FOKRKI51hTQMxOs6H/+1xqw5CKKKJCwBi3aBYhkVZN2dz3UScOY1jf9N0nW",
	"3dwa7BwX5hbC1HxeoYWP+ZUCVyIRFoWF16WxiqbNmvh+2A9vqyW+EfHfcZgtP9RjYSDiGonQcUCIUeh5",
	"0w31rJGlRePupKi/2r8+cNaOtYUiFyjJ87YB45mmM1Im0SgzqrkpCHKKiQduVJGgvHB2+5hlIeTNbBNV",
	"UOOwYsabwQczJTQn821uFlDck5U90SC/Bp8NCO5r4HlSqctPIJcGnf1MqmIWzrTilWfm1SCzRCA/sxY9",
	"pgf8oi06o6pDXQtoxqz0XeNMODiMuyjUm4qm+yUgXcWquiVQGakqs50HCPmaudPsipYZNS9Wsl3FixRc",
	"cU3eTqHJvKcxEoleIYxadivIaa94e8nWrIBbI+n9I2mkKDRk7nSD0VR5mIjjqDK9Tu4eT+xAvKeQ28X+",
	"O4YrxmOUWifd2zHOuYc+YH6FsEg+s7MEDndncZjQeOXQXAzuUyIJ9sgfumIwXt2MPp2/T3bYVqlhnDHq",
	"rboT/M310UeBvzMre6sgMIllhO8KhUtafPhIXGU5fg3UNVBvFFBvGJaR1PUbt7gueim3ugxiHSjEMnsU",
	"LFGrY16oa3XqWp2NqNXZSzbKq6t2HknVzszmBHXVTj2wX1ftbEDVTi62WFS1o12AvWrHtNH6pv8us17P",
	"LLu/szlZTaJ1TvbzAam4qibiYfPmZJ+oC78u2kTtuus52Xvhy3inek622pwszh8/VQGK9m1QZA4SbpiD",
	"hEurSc/BZ1HOjV2XRFu/4/RgXmFWl8fIlRsWtg8H16C1joUWz1Yux68V6860yjN6Xsbu2s2DxTMO5xB4",
	"elOnwkfMQIHMHhfAKIgNNatq0yJ+6EkSYC5bI8b9RnGXPoSAmk2UioY0Ih6IWeuC28BjLhRITkiXU73N",
	"L+N+hekX2151JZ8vWIJ+yvJQtKMqGhKK+dTygGUzwQXCnr1d3EbQ/KfPsSun+oT5Pm4IUEYnwY1es7xV",
	"PAZvb/as+0pU547HW4U+87reyHUhnfq8ub3iQfoVaCwemhP/17CquFHgyHLbItGZjRTt5oT+LBGA9YHc",
	"9x7G7NtcG6+GEDtb1Uz/bnDjdehdoTAQwKMcenX4KI1bWt/03yrrYeIIhs4JYDY/fimQp+0DaQOxEnn8",
	"QvJqREY6qIOsOouus+gHs0XQxuXPFyZ/frtG/hznNKnbXwaPyvPoVhxftL6pXzqmWQqasniUH/JNIpcn",
	"AE3vY15PmAvo2euTM9R9YZl+zB8FPYfORBE1Pt1Fh0HDaWKLy40FdMxYQGgfCjh2dQUlj0cEluwM5eX/",
	"daf4jp3ijoYwVhtdqDS4sMrYQkkqXjjq3vrp9+op9Aya42ac+/+1wvjAXebcKyXP6M/FpD/8slR7/ns3",
	"bvHTnPR2OYdojyfyB3tWG5OP36kH4X+oidkP1H+aWWK9YqeegX0s2zHE7nK9oNg42UJblVz/wcJIODsp",
	"ljp2HQCbTz7DkvnEQWefLpGKjEzF6EbHwve1dqjo4cvXCcXPWieWqi0MmtPEww+51sLDDV37o5Ja023j",
	"2m7tZ5ODouqQoA4J6pDg/kICs/pi3ZDAeL41QgJruXArm/0tyATjUbqZsuEbIid6WVK+fnlDsr4Fm/0Z",
	"Bp7sZn91bW8NJTWU3FN2mS3PXSe1XAI+Dq3okZzxvcxQYvJSPZb4Q03yIpL7DyjnTVS8hIUdLVPKm9pQ",
	"Xcdb1/HWdbx1HW9dx7tyHW8MDPddxbsSaiyOS1rf4p/LVPAmlDy5kt3YFKwUXnTDYTUKU6HXYVSdGtcF",
	"u3XB7kMv2I091hLQ87IEetaq1M1AUF2lW16Q+IRLdH9QWp/Y42rVuUdLFucuaf+L9wWt+0FdlVtX5T6R",
	"qlxbNvsdanJXCBiO5tTjyknoDykmkVXNc5HRDLCcqP+jN+KNks2uyXBLhN4w0ZKvbpiHvEfXU1DXj/U/",
	"87t8QtZK/f4RdfDFu2kZQ9WzAtG2lxbJbNh53spv6+ApX/JX13vVk/T1JP2PMtPkiIao3mukZ+3votqr",
	"6L+qxBrPM5FGnDKV7Hv9E0jkEaE3WhZhEDCenQcxBeLFIfrHMcGRaNQIJD4/YJBw04y5tKl5hamQ3Daf",
	"SSFumtMmQl2s0ViByx10ZY71iGNAY5aZUz4QHkngmYq1+BnJkJCMp3k9qjLGdF918yV9t6Bpw2LzZIkD",
	"sT5n5XdHx2JVbfOxB2H1mRt1nFXHWfc1m/UkD8f6MYdh2YOt7ixWL3sYVh6tqWvOtMiekGUCsGhBeEav",
	"qn3gDxmqtdA+LXUWVg4o7/BErGXaffggvFIM1K8PzaoBvD40qz40qwqyHWyZPcVFb6uBQu71UGvLvFeY",
	"H9jZ3X0dEs9F7pRinzhIMIdgD8FtAJwAdUA0d3f/NuR/V/+fArgCYQ7m6B5QyZDngaPaMjSwETpjQgp9",
	"MJDBwFF8/KWe4QCu0M2LF8RhzkIBntjTOSwBsYcYj4mQxAePUBDmOIu32Jno1rV5YEIFmrKQIx9cgtEz",
	"0yLjZm7lrxqNiRQIC92cBBf5ILGLJW4qWZrJDc2SRSrxuBB1QNHGAfsoAD4CR3pThOn0ZgIcMrI57395",
	"v7Mj9NlPnkfGQA0kRWdV6/OwSKD5QZhib/oHRPQnsQGSHFNhCleJ1IJjgSQ+9tDXEHtEGm+gnlSkMO5j",
	"6kAT/QrIgIWeZDKR0C2RUySY+gJyMEUueOQa9IklhgsUeHg6jLemSfWN4Br4VMs+I6bIzGbl9CZqd4SF",
	"3MtIyEyWKKGbwx8LklKRDvOxtoVo6Z1hQURTY5rxCOL3otaU3pVR60tKCpeT0B++w2KCxkCj7Q6a6NiL",
	"5teMSSpz1b3BRdcEIyXxsceG2EMnb/6ZHFzqAvZQKIBnRJHhPzqbbuv/AwAA//+oaftuudkAAA==",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
